### PR TITLE
Replace icon with logo with text

### PR DESCRIPTION
**Pull request by rugk**
* [x] I agree to release the changes in this PR under the Zlib/libpng license as shown in the  [LICENSE file](https://github.com/PrivateBin/PrivateBin/blob/master/LICENSE.md#zliblibpng-license-for-privatebin).

## Changes

* Remove icon.svg with logo.svg
* Change templates to use new logo including correct size (225px width)

## ToDo

* [x] The icon does not look so nice in such a small version (thick border), needs to be updated

### CODE REVIEW

**Comment by elrido** [comment]
There seem to be some conflicts and could you also replace the icon in the main README?

**Comment by rugk** [comment]
It is already replaced in the Readme.

**Comment by elrido** [comment]
Sorry, we probably were posting simultaneously.

**Comment by elrido** [comment]
I have to say that the logo with text in the template looks awful (in browsers) and is way too large. Couldn't we just keep the icon and make it a bit smaller (38 pixels instead of 42)? On the README.md the logo with text looks OK, so we can keep it there.

**Comment by rugk** [comment]
> is way too large.

Well... previously where we had no icon it was similar.

We can of course revert this PR and use the icon.
It just matters what you want: only the icon or do you want to have the text? If so we could adjust the size again and make it less intrusive, of course.

BTW: On mobile view we should probably always use the icon only.

**Comment by elrido** [comment]
Ok, how about we keep this current logo as the 500px version for README, but create a second one without the text and in size 38px (just the icon with that size setting in inkscape). We then simply keep the "PrivateBin" as text next too it. That will work in the bootstrap, darkstrap and page templates.

We can then still review the mobile version to see if we need to remove the text or not in it. There should be enough space even with just 360 pixels width, since the menubar disappears into the hamburger menu in that mode.

**Comment by rugk** [comment]
The height should be 42px, 38 is a bit too small, but yes we can create one here.

So I'll revert this PR and add the icon again.

**Comment by elrido** [comment]
No need to revert it, just create a new one.

42px is to high, the hexagons tip almost touches the viewport. For good design there should always be a space of at least 3 - 5 pixels to surrounding elements (the text part of the logo next to it can be tighter, it is part of the logo element group).

**Pull request merged**
