### PR TITLE
Try new RegEx for creating links

### PR DESCRIPTION
**Pull request by rugk**
This PR fixes https://github.com/PrivateBin/PrivateBin/issues/331

## Changes

grafik

## ToDo

* [ ] Test

### CODE REVIEW

**Comment by rugk** [comment]
Okay, so Mocha complains about:
```
urls2links
         replaces URLs with anchors:
     Error: Failed after 7 tests and 10 shrinks. rngState: 866b9d4c357e2fa801; Counterexample: ""; "http"; ["j"]; []; []; ""; 
 urls2links
         replaces magnet links with anchors:
     Error: Failed after 1 tests and 7 shrinks. rngState: 063950d1eb6ac8f274; Counterexample: ""; []; ""; 
``` 

So are these "counterexmaples" examples where the text has been replaced, and should not, or where i8t should not be replaced, but has been? Because all these are obviously no valid URLs…
I guess the test `'ignores non-URL content'` is supposed to generate non-URL content and test for it, so the tests above are supposed to match:

So I guess the tests need a bit fine-tuning here… :smile:

**Comment by elrido** [comment]
So, what the unit tests tell you is that the new pattern doesn't support http or magnet links. The two shrunk patterns that trigger the issue are:
- `http://o/?#`
- `magnet:?`

**Comment by elrido** [comment]
PS: You find the test logic here https://github.com/PrivateBin/PrivateBin/blob/master/js/test/Helper.js#L91

As you can see, the URLs are randomly generated based on different types of strings and then catenated together.

**Comment by elrido** [comment]
Looking at the regex, I see no reason why it barfs up on the http URL. For the magnet links, which have quite a different format, you could just stick the original Regex at the end:
`|((magnet):[\w?=&.\/-;#@~%+*-]+))`

**Comment by rugk** [comment]
Actually I did not change the RegEx of the magnet links… Okay found the magnet link issue, the RegEx always uses the first matched group and this was a group around everything…

Already looked at the test logic, but the name "counterexample" confused me. Actually it is just the example where it fails, not a "counterexample"…

`http://o/?#` is _not_ a valid URL. A minimal working example would e.g. be `http://o.co/?#` (also one-char TLDs are not allowed so `http://o.c/?#` is also invalid).

**Comment by otaku** [comment]
I'm pretty sure single letter TLD are valid according to RFC 3986 / RFC 1123.  Domains that have a single digit are not however

**Comment by rugk** [comment]
Okay, theoretically maybe, but in reality there are none: https://stackoverflow.com/questions/7411255/is-it-possible-to-have-one-single-character-top-level-domain-name#21872376

**Comment by elrido** [comment]
Not just theoretically: I can have that hostname in my /etc/hosts or add it to my routers DNS overrides. This is a valid hostname that I would expect to work and that was working before. Please fix it.

**Comment by elrido** [comment]
The case that it found now is this: `http://w/?%` This is a non complete URL encoding, the percent would have to be followed by two hex characters. The [relevant](https://tools.ietf.org/html/rfc3986#section-2.1) [RFCs](https://tools.ietf.org/html/rfc3987#section-3.1) say SHOULD use upper case, so it would be `(%[0-9A-F]{2})`. The previous Regex would happily convert this into a link.

Now, I agree that this is not a proper URL, but it is working in the sense that I can append a `?%` to any working URL and it will still display that site, as there is no GET parameter to parse for the server. The purpose of our Regex isn't to _validate_ URLs, but to detect anything that would yield a valid result in a browser and link it. The one corner case that I can think of is punctation (commas, dots) just after the URL, which we don't want to include in the links. Other then that we may be quite permissive. We still do the DOMpurify after, in case someone sneaks in a URL that resolves into JS execution when clicked on.

**Comment by rugk** [comment]
> just after the URL, which we don't want to include in the links. Other then that we may be quite permissive.

**Comment by rugk** [comment]
> just after the URL, which we don't want to include in the links. Other then that we may be quite permissive.

Totally agree! :+1: Actually the last thing this RegEx is really good at though…
May still be a bit restrictive though; I admit.
So what about using the same RegEx as showdown uses (maybe slightly adjusted to our use-case though), which I've suggested in another issue? Or can we maybe even hook into showdown to only do this processing stage(?) – I doubt so, but mhh…

**Comment by elrido** [comment]
Weeell... we could use the original Regex to extract a potential URL, feed that bit to a Showdown object with just the URL bit enabled (to make it process as fast as possible) then replace the extracted bit with what showdown returns us. Obviously much slower then the current solution...

**Comment by rugk** [comment]
…and totally circuitous…

**Comment by elrido** [comment]
I have expanded the unit tests to cover the exclamation mark character in the hash part of the URLs and reverted to the old regex just to prove the unit test catches it, then added the missing character to have the unit test working.

@rugk: I don't want to revert your work here, there may be value in switching to a new regex, as long as it works. Remember that we don't need a validation regex, just one that finds potential URLs. Validation / security is handled using DOMpurify.

I merge the temporary solution down to master for now, but leave this PR open so you can continue your work on the improved regex. Mine doesn't cover brackets yet (i.e. wikipedia links), so you may want to expand the generated characters in common.js with those and revert to your regex. [Janitor](https://janitor.technology/) is really handy for such work, as it includes mocha!

**Comment by elrido** [comment]
Sorry, github insists to regard this as closed, because I merged. I'll just push another commit to it, which reinstates @rugk's regex in the hopes that github will reopen it.

**Pull request merged**
