### PR TITLE
Adding NL (Dutch) translation

### PR DESCRIPTION
**Pull request by micschk**
This adds a nl.json file & udpates the array of available languages in privatebin.js
The security hash for privatebin.js needs to be regenerated & updated in the template files

### CODE REVIEW

**Comment by rugk** [comment]
A translation seems to be missing so our tests fail:

```
There was 1 failure:

1) I18nTest::testMessageIdsExistInAllLanguages
message ID '%s is a minimalist, open source online pastebin where the server has zero knowledge of pasted data. Data is encrypted/decrypted <i>in the browser</i> using 256 bits AES. More information on the <a href="https://privatebin.info/">project page</a>.' exists in translation file nl.json
Failed asserting that an array contains '%s is a minimalist, open source online pastebin where the server has zero knowledge of pasted data. Data is encrypted/decrypted <i>in the browser</i> using 256 bits AES. More information on the <a href="https://privatebin.info/">project page</a>.'.

…/PrivateBin/tst/I18nTest.php:171
```

**Comment by rugk** [comment]
Ah, you seem to have missed replacing `PrivateBin` with `%s`in other strings, too. Please just have a look at the tests/run them (or look at Travis-Ci). It seems they only return one translation issue at a time…

``` 
1) I18nTest::testMessageIdsExistInAllLanguages
message ID '%s requires php %s or above to work. Sorry.' exists in translation file nl.json
Failed asserting that an array contains '%s requires php %s or above to work. Sorry.'.

…/tst/I18nTest.php:171
```

**Comment by micschk** [comment]
🤦I give up. 
Hope someone else cares to fix the remaining issues and pull in the Dutch translation.

I've never had so much trouble contributing a translation. IMHO these errors are due to:
- **a missing single source of correct translation keys** (there's no en.json?)
We initially took the de.json from our install but that's missing a few lines as well as the '%s' replacements
- **translation keys which are very long and prone to breakage**
What if someone changes a single char in one of the english strings, I think currently this would break all translations? Wouldn't it be better to work with short key-like constants/strings as keys and then having an en.json for the actual full sentences?

**Comment by rugk** [comment]
Oh, indeed there is no `eng.json`. That is really bad, I see. All the points you say are valid, IMHO. Also the strings are long, that's not okay.

I've created https://github.com/PrivateBin/PrivateBin/issues/316 for tracking this problem. 

As for this PR, is it intended you reopened it? I'll tag it with "help wanted", so maybe someone may continue the efforts here.

**Comment by micschk** [comment]
Yes, I accidentally clicked 'comment and close'... Would be great if
someone fixes it :)

Op ma 21 mei 2018 18:38 schreef rugk <notifications@github.com>:

**Comment by elrido** [comment]
FYI: There is intentionally no en.json. The php unit tests do check if there are any message IDs in any language that are missing in the others and would fail if this were the case. So instead of an en.json you can just use any translation file of any commit that passed the travis CI checks.

**Comment by micschk** [comment]
I understand, but this creates a difficult and fragile dependency structure (right?).
Say a new string gets added in English; basically this would make the test fail until it gets translated in all available languages (chicken-egg/catch-22 situation).
Same when a string gets changed in English, all translation files would need to be updated with the new key.

Usually how I'm familiar with translations being structured is roughly like this (a key run through a function along with a fallback string in case a translation is missing in a certain language file):

JS:
```translate("WELCOME_MESSAGE", "Hi there, how are you?")```

Yaml (Dutch):
```''WELCOME_MESSAGE": "Hoi! Hoe is het?",```

**Comment by elrido** [comment]
This a question of workflow and the way gettext like translations are used since the 90ies: When a new translation string is first introduced, it has to be added to all translation files or the unit test will fail. So the unit test enforces that developers adding a string don't forget to commit it to all files and not just one.

Contrary to the generic IDs that you suggest it is less fragile: The user always sees a readable message, just by default an English one in case it isn't translated yet.

Translators can also easily find new messages, since these are just appended to the end of the translation files. Just look for new messages in nl.json that are still in English.

**Comment by micschk** [comment]
Well, we also didn't have yaml in the 90's ;-)

But really I'm very happy with PrivateBin as-is, and it's OK if my suggestions are not agreed upon. I'm just making them based on my own struggle to contribute a translation file.
- Still think using keys this long is fragile (my suggestion also includes the English string as fallback, like you describe)
- And using shorter/constant keys, you can still require them to be present in all language files (but they will not break if you change a comma in the English/original translation strings).

**Comment by rugk** [comment]
Hey, could you please discuss these things in https://github.com/PrivateBin/PrivateBin/issues/316. This PR here is about the NL localisation.

**Comment by elrido** [comment]
Hi again,

Thank you very much for providing the translation!

Given the types of errors that the unit tests complained about, it may be that your editor gave you an extra hard time, since it seemed to have expanded some of the ellipsis characters ("…") and replaced bits in the message IDs.

Anyhow, it should now all been fixed and our next release will finally include Nederlands!

**Comment by rugk** [comment]
@micschk BTW, remember to subscribe to https://github.com/PrivateBin/PrivateBin/issues/201 to receive further notifications when updates to the translations are needed.

**Pull request merged**
