### PR TITLE
Make Opengraph really functional

### PR DESCRIPTION
**Pull request by ZerooCool**
3 URLs of images used on social networks are passed in absolute URL.

Note that I did not pass all the images in absolute URLs, but, it could be consistent to do so, but, if the images work, maybe a relative call is more efficient?

Remove the version of PrivateBin, at the end of each image. This apparently prevents the opengraph from working, and, so I deleted on all of the images, to remain consistent at this level. This will make fewer requests, and, anyway, the images are not intended to change with each version.

### CODE REVIEW

**Comment by r4sas** [comment]
Isn't better to get subdirectory from PHP?

**Comment by ZerooCool** [comment]
@r4sas And ? Have you read ? This is the good comment, in cfg file, no ?
; The full URL, with the domain name and directories that point to the PrivateBin files

**Comment by r4sas** [comment]
I'm about other thing:
I have one installation of PrivateBin which accesible from few domains. If we introduce `path` option, that means that we will have one URL for all domains in opengraph and twitter card.

That's why I suggest to use PHP for such things:
```php
$port = ($_SERVER['HTTPS'] == 'on') ? ($_SERVER['SERVER_PORT'] == 443 ? '' : $_SERVER['SERVER_PORT']) : ($_SERVER['SERVER_PORT'] == 80 ? '' : $_SERVER['SERVER_PORT']);
echo($_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['SERVER_NAME'] . ((!empty($port)) ? ':' . $port : '') . dirname($_SERVER['DOCUMENT_URI']) . '/');
```

**Comment by ZerooCool** [comment]
For your first pb : You can read this ( use a translator )

https://wiki.visionduweb.fr/index.php?title=Le_fichier_robots_txt#Emp.C3.AAcher_l.27indexation_d.27un_site_miroir_cr.C3.A9.C3.A9_sur_un_sous-domaine_via_le_fichier_robots.txt

As said, only 3 links, will use the new path, these are the 3 images, for opengraph, therefore, you can perfectly create a rule for redirecting its 3 images, depending on the provenance of the visitor, to give the correct image path, I did not test, but, I think it should not disturb PrivateBin, and, work.
In fact, we would have to test, but, I think that the Apache redirection would be carried out last, therefore, functional, with an image A for the domain A, and, a image B if we come from a domain B that Apache will redirect from A to B, thus, the configuration of Opengraph should not pose any difficulties, and, the link will always be in absolute (what it takes for Opengraph) but redirected thereafter by Apache.

It is not the problem of PrivateBin, to know if you have created a multiple instance with several domains on the same instance, I think that you must see on your side how to work around.

**Comment by ZerooCool** [comment]
Regarding your proposal, my level of use of PHP does not allow me to know if your proposal is reliable in terms of security, variables, use.

My proposal had the advantage of being simple, accessible to the user from the configuration, which may or may not be entered. (Certainly if the user does not enter information, opengraph does not work.) On the other hand I removed the version of privatebin behind the images, which also seems really not to be necessary.

I brought you a solution, in my last message, to answer your problem of multiple sites. I don't think it is up to privatebin to respond to this problem, but it's up to you to know how to redirect.

In my opinion, my PR is sufficiently clear, to deserve to be integrated, because, for an administrator even unconfirmed, it will be clearly legible: One site, one path, then opengraph works.

I can't guarantee that using relative URLs is the best thing. I think this is better, in terms of performance. In any case, when developing in HTML, this is better to guarantee the portability of a project, to another domain.

Here, the variable "path" being made available from the site configuration, the project remains perfectly portable. Since only 3 urls are rewritten, this will not affect performance.
We could only use absolute urls, at least for the consistency and aesthetics of the code, but, I have no RFC to rely on, to say to do like this, and, I guess (I could be wrong ) that absolute URL requests could be a bit more demanding than a relative URL request.
This could be verified, but, if my proposal does not pose any security or performance risk, I simply propose to accept it, even if it means opening up a new problem to improve it later.

**Comment by rugk** [comment]
IMHO we should combine both solutions. Allow admins to overwrite the `path` variable, and if none is set, automatically detect the domain with PHP. (which could have it's own issues with reverse proxies or so, but I don't know…)

**Comment by ZerooCool** [comment]
This is why in my proposal, finally, we find ourselves at the current stage, since, by default, I did not activate the choice of a domain, on the other hand, the administrator only has to inform the path, and, at that time, the opengraph works.

In addition, my proposal cannot entail a new security risk, since I base myself on the existing model object, which should not be able to be compromised I think, if it is well designed, and, I suppose that it is.

On the other hand, using the SERVER variables, and, the identification of an IP to serve as PATH seems a bad idea, it would be necessary to be able to recover the exact URL address, and, it is not sure that this is possible, c is as if I was trying to find out where the visitor came from, am I wrong? This origin cannot be known, with PHP, but only supposed, if the customer is willing to send the information back to us, and, again, does it have to be true?

Thus, I propose to push my proposal, which remains simple, but functional, which allows to answer this problem of opengraph, without complicating the work of the admin, who will find the information in the parameters of the configuration file.

**Comment by elrido** [comment]
The [PHP unit tests fail](https://scrutinizer-ci.com/g/PrivateBin/PrivateBin/inspections/c34e900d-131c-49b4-b1f8-a9835beb3a4f), because `PATH` is already in use for [changing the (relative) directory PHP files get included from](https://github.com/PrivateBin/PrivateBin/blob/master/INSTALL.md#changing-the-path):
https://github.com/PrivateBin/PrivateBin/blob/0673c1cde17a834e522399ff17e40588aaa4db0a/index.php#L14

I suggest to use a less ambiguous term, maybe `URL` or `BASEURL` or `URL_PREFIX`?

**Comment by ZerooCool** [comment]
Ok, i make that.

**Comment by ZerooCool** [comment]
PR UP.

**Comment by ZerooCool** [comment]
https://github.com/PrivateBin/PrivateBin/pull/664/commits/e61c44ef466c802581f3f72b5e8f712262965a82

**Comment by elrido** [comment]
Sorry for the delay on our part. I did change the alignment of the new default value to make the StyleCI test happy and changed the tested value to an empty string - the unit test didn't complain about it, since PHP will silently convert `false` to an empty string when you use it with a function that expects a string, like `echo`. I only changed that for consistency.

**Pull request merged**
