### PR TITLE
helm chart for privatebin

### PR DESCRIPTION
**Pull request by bdashrad**
## Changes

* Adds a helm chart for easily deploying PrivateBin to kubernetes

## ToDo

I originally was looking to add this to the [helm/charts repository](https://github.com/helm/charts/pull/13622), but after discussing it with some members, they would prefer projects to run their own helm repository, since the core repo is large and difficult to maintain. Information on setting up a repo can be found here: https://helm.sh/docs/developing_charts/#the-chart-repository-guide.

### CODE REVIEW

**Comment by bdashrad** [comment]
@rugk I can change it to use the docker tag `latest`, or it could be maintained as a separate repo, and updated after the docker image is updated. Usually charts are maintained separately, but I wasn't sure how you wanted to do it. I'm happy to close this PR and push it to a new repo and have you fork it.

**Comment by bdashrad** [comment]
@rugk i have the same chart separate (and with corrected paths in the readme) here if you'd rather keep them distinct: https://github.com/bdashrad/privatebin-helm

**Comment by elrido** [comment]
We had moved our various docker containers into separate repositories, i.e. https://github.com/PrivateBin/docker-nginx-fpm-alpine. I could fork of yours into the project namespace or would you prefer to merge your changes into the docker image repo?

I think it would be more robust if the version is explicit, even if that means extra changes on releases. A benefit of containers is the possibility to create immutable and reproducible infrastructure, which I do feel the use of `latest` tags undermines. It works now, but will it work in a year?

**Comment by bdashrad** [comment]
@elrido i think forking it to it's own repository under the PrivateBin org would be the best scenario, and defaulting to pinning the version as listed in `Chart.yaml`. I have updated my repo to maintain a chart repository for PrivateBin, hosted in github pages. If the repository is forked to the PrivateBin org, the URL in the README and in the Rakefile will need to be updated.

**Comment by rugk** [comment]
AFAIK you should also be able to _move_ a repository, you do not need to fork it.

**Comment by elrido** [comment]
I just fork them as it is easy and shows the originator some kudos. Of course we can later detach the fork if the fork keeps getting maintained more.

**Comment by bdashrad** [comment]
@elrido i will push up the standalone version I have to that repo. I set up travis-ci to build the yaml and the chart releases automatically, we will need to set a private access key in the travis-ci config if we wish to continue to build it this way. We could also use the Rakefile to do the releases and the yaml on the client side then push up.

**Comment by bdashrad** [comment]
i pushed up my code to that repo. I'll close this PR now.

**Pull request closed without merging**
