### PR TITLE
Add missing Dutch translations

### PR DESCRIPTION
**Pull request by AnonymousWP**
## Changes

* Add missing Dutch translations
* Fix Dutch spelling and grammar mistakes

### CODE REVIEW

**Review by elrido — APPROVED** [review]

**Comment by elrido** [comment]
Thank you for the update!

**Comment by rugk** [comment]
Please do note though, that you can also use the simple online tool _Crodwin_ for translation. See https://github.com/PrivateBin/PrivateBin/wiki/Translation We normally use that and it periodically syncs the translations back to this repository.

**Comment by AnonymousWP** [comment]
> Please do note though, that you can also use the simple online tool _Crodwin_ for translation. See [out translation guide in the wiki](https://github.com/PrivateBin/PrivateBin/wiki/Translation) for more information. We normally use that and it periodically syncs the translations back to this repository.

I am aware, but afaik it requires an account, so I prefer to do it this way, by making a PR.

**Comment by r4sas** [comment]
You can easily authorize on crowdin using your GH account.

**Pull request merged**
