### PR TITLE
Facebook tracking parameter test & fix

### LINKED ISSUE #396: Facebook tracking parameter break url when shared link is clicked
## Disclaimer

I am not a php developper and haven't taken time to dive into the code, I searched unsuccessfully for similar issue but I maybe missed something. 
If the problem I am describing is unsolvable or already in dev pipe or has already been discussed and won't be solved be free to close this.

## Steps to reproduce
This has been encountered on https://www.privatebin.net and I haven't taken the time to try reproduce it neither in a local instance or an other public one

1.  create a paste and generate the link
2. share it on facebook 
3. click the link

### What happens
Facebook add a `fbclid` url parameter which break privatebin routing

### What should happen
In my humble opinion, the router should be able to remove such parameters or at least to ignore it since it is a common practice for social networks to add such tags for tracking purposes.

### Server address
http://www.privatebin.net

I can reproduce this issue on <https://privatebin.net>: Yes / No

### PR DESCRIPTION
**Pull request by elrido**
This implements test to replicate and fixes #396.

### CODE REVIEW

**Comment by elrido** [comment]
I hope you have seen that I added test cases that generate random parameters in front and after our always 16 character long hex value. These tests now all pass (in JS every test case means we ran 100 random cases).

The only scenario I can think of that would still fail is if a parameter containing a 16 or more character long hex value gets added _before_ our key. I am happy for another solution, as long as it passes the tests.

**Comment by rugk** [comment]
Yes, the tests are all good, but well… even if it is a low probability (which your tests somewhat confirm), it may happen. Also Facebook may decide to just change their ID in the future and then they e.g. just use Base64.

**Comment by rugk** [comment]
Mocha failing at not-modified code-places with `document is not defined`… What?!
I'll look at that later… or it is just some random thing, who knows.

**Comment by elrido** [comment]
When only one of the 6 tested environments fails, it's usually a heisenbug. I relaunched that job in travis an we can see if that solves that issue. TravisCI isn't always super stable. Sometimes it has networking issues that break the tests or the tests fail randomly. I then relaunch them or retest locally to see if I get a consistent failure.

I'll look into your changes later on and let you know.

**Comment by elrido** [comment]
Looks good, will merge it this evening.

Thanks!

**Pull request merged**
