### PR TITLE
WASM streaming / eliminate unsafe-eval

### LINKED ISSUE #814: Make WebAssembly loading (for zlib) possible to use in Chrome/ium with a stronger CSP
The goal is to remove `unsafe-eval` from the CSP of PrivateBin.

## Reason it is included

> The `unsafe-eval` is required in Chrome and Safari for WASM loading. If not set, calling WebAssembly.instantiate will trigger an error in those browsers.
>https://github.com/PrivateBin/PrivateBin/blob/8232dce395e421450779bd710e5872399f792085/js/zlib-1.2.11.js#L34-L35
>
>- [Technical background](https://github.com/WebAssembly/content-security-policy/blob/master/proposals/CSP.md#summary-of-webassembly-apis-and-their-risks)
>- [Browser comparison matrix](https://github.com/WebAssembly/content-security-policy/blob/master/proposals/CSP.md#behavior-of-current-implementations)
>- [Proposal to W3C to standardize `wasm-eval` directive](https://github.com/w3c/webappsec-csp/pull/293), that Chrome has implemented for web apps, but not web sites, that would allow to restrict eval while allowing wasm. It hasn't been accepted and even if it will, it will take years for browsers with support for it to be rolled out for a majority of users. :-(

https://github.com/PrivateBin/PrivateBin/issues/108#issuecomment-821773679

**Edit:** As it turns out, [the change cannot actually fix the CSP problem](https://github.com/PrivateBin/PrivateBin/issues/814#issuecomment-864543105).

## Potential solution

> Regarding [`unsafe-eval` the Matrix Element client has the same issue and someone suggested](https://github.com/vector-im/element-web/issues/12262#issuecomment-864274860) this:
> > Using `WebAssembly.instantiateStreaming` would avoid this problem.
> 
> ---
> 
> Also [the docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming) for this say:
> > This is the most efficient, optimized way to load wasm code.
>
> So would likely not be a bad idea to use this altogether…

https://github.com/PrivateBin/PrivateBin/issues/108#issuecomment-864372271

### PR DESCRIPTION
**Pull request by elrido**
This PR fixes #814

## Changes
* switches from static WASM loading to streaming instantiation - this requires the server to deliver the WASM as `application/wasm` MIME type, which can be configured if older apache or nginx servers are used that don't do so by default
* removes the `unsafe-eval` CSP (which is the main motivation for this change)
* but had to add the new `wasm-unsafe-eval` CSP - at least Firefox requires this for WASM to load at all, regardless of method
* removed eval-use from legacy.js, where it was used for feature detection. Without it, a browser without async support would not be able to parse legacy.js and the "Loading..." message will not disappear. Other detections still work.

## ToDo
* [x] document change - this will break things in old browsers and old servers
* [ ] we could consider keeping the more robust static instantiation as `wasm-unsafe-eval` would allow that as well

This is a quite a drastic change for a small benefit (changing CSP from `unsafe-eval` to `wasm-unsafe-eval`, eliminating a warning in Mozilla Observatory and similar scanners). Please discuss if you still feel it is worthwhile or maybe to be toned down in scope?

### CODE REVIEW

**Review by rugk — APPROVED** [review]
I like this!
* it simplifies the code
* it increases the strictness of the cap and thus security (though yes I know Eval has not been productively been used before, but anyway, maybe some admin included custom js? Good will make them aware of that fact.) 
* it modernized the code

So yes I see your concern about sysadmkns needing to re-configure some things, but really, we've waited for very long. Wasm should now be served by this (correct header) by default. And if it is not, you're probably using some outdated server, so you may not want to use that Private Bin instance anyway. 

Also admins could forget to adjust their custom csp? Though, AFAIK, having the old Eval in there would not hurt, would it? So this would not be actually be problematic.

> this will break things in old browsers and old servers

I mean really, which versions are affected. Or issue has been open for years for this, so I guess most are not a problem. Legacy browsers are anyway hardly a thing as most autoupdate and esr versions exist but well. Servers may rather be problematic as being long life in a pre-container world but hmm.

**Comment by rugk** [comment]
Yeah my question for servers was more about "when do servers decided to ship this producively", so we don't have  an influx of tickets/questions when PrivateBin does not work (anymore) due to this thing missing in the config. YOu've listed the tickets here already: https://github.com/PrivateBin/PrivateBin/issues/814#issuecomment-2138730495

For Apache you can just do the git blame online, and it finds this: https://github.com/apache/httpd/commit/00b2bd14044327a1e1b0407aa2771e8b1a4b31ac PR https://github.com/apache/httpd/pull/332

This is "only" Jul 7, 2023 aka around a year.
Newer releasses exist: https://endoflife.date/apache but supports a version from 2012 so well… dunno how long we would have to wait here.

As for nginx https://trac.nginx.org/nginx/ticket/1606 was fixed 2021-08, [a version long ago, not supported anymore](https://endoflife.date/nginx) so there are way shorter release cycles.

**Review by rugk — APPROVED** [review]

**Comment by cryptomilk** [comment]
You could add `AddType application/wasm wasm` to:

https://github.com/PrivateBin/PrivateBin/blob/master/.htaccess.disabled

**Comment by elrido** [comment]
> You could add `AddType application/wasm wasm` to:
> 
> https://github.com/PrivateBin/PrivateBin/blob/master/.htaccess.disabled

THX, done in 654bff65cc7c448d78f08dc5b8d24c286351cd96

**Comment by rugk** [comment]
Just FYI I hope this works when it is already added, so re-adding again does not hurt?

**Pull request merged**
