### PR TITLE
adjustment of one translation by split it, to avoid the use of the i html markup

### PR DESCRIPTION
**Pull request by hogren**
This PR fixes a problem introduced with the commit eb32ea141956c0ed72e3186956895333f62e271c.
In the sentence "Data is encrypted/decrypted in the browser using 256 bits AES.", we saw "&lt;i&gt;in the browser&lt;/i&gt;" in normal font style in place of "<i>in the browser</i>" in italic.

## Changes

As discussed on the [PR 754](https://github.com/PrivateBin/PrivateBin/pull/754), I firstly just split the unique sentence with &lt;i&gt; markup.

## ToDo

* Remove all other markups present in translations
* Remove the escaping mechanism of <a> markup form I18n libs (PHP and JS)

@elrido and @rugk, are you ok if I continue in this way ?

### CODE REVIEW

**Comment by elrido** [comment]
I think this change will make it more difficult for translators, as the sentence is now split in two parts and for example on the crowdin translation website the strings are not necessarily presented in the order of the json files.

What I had proposed was to keep the sentence in one piece and have the %s as stand-ins for the start- and end-tags. Example:
```
"%s is a minimalist, open source online pastebin where the server has zero knowledge of pasted data. Data is encrypted/decrypted %sin the browser%s using 256 bits AES."
```

My other question is why you want to do this in the first place? This one sentence is currently displayed correctly, as far as I know (it's the one on the bottom of the [demo page](https://privatebin.net/)). Could you show us (screenshot and/or link) where the current solution with the inline-HTML causes an issue, please?

**Comment by hogren** [comment]
Sorry @elrido , I good understood your idea. I just followed the last comment of @rugk .

As mentioned, the problem appeared in a recent commit (after the last release). The &lt;i&gt; was good interpreted because, before the commit, there was a &lt;a&gt; in the same sentence and it was sufficient to not escape html tags.

I will follow your precedent idea.

**Comment by elrido** [comment]
Thank you for explaining and sorry for the confusion we caused. I see that this is indeed a regression in the latest master version. I think it was inadvertently caused by eb32ea141956c0ed72e3186956895333f62e271c.

Thank you very much for reporting this and working on a solution!

**Comment by rugk** [comment]
Please do also note one _important_ precautionary warning of me: In case you did not notice, you have committed (i.e. created commits) with potentially sensitive data like your (full/private) name or mail.
Anyone, who clones your fork/this repo can view these private details, exactly as you've committed them. Also, if this PR gets merged, this will stay in the (commit) history of this project and will thus hard to be removed later.

So if this was unintentional and you want that data to be changed/removed first, better do it now. :smiley: [Here is a good resource](https://stackoverflow.com/a/750182/5008962) ([actually from GitHub's help](https://help.github.com/en/articles/changing-author-info)) on how to change your name/mail afterwards.
Also note that when setting your git [username](https://help.github.com/en/articles/setting-your-username-in-git) and [especially your email](https://help.github.com/en/articles/setting-your-commit-email-address), you can actually write/choose anything there. As for GitHub, it is recommend to use your GitHub username and – if you want to keep your mail private – the GitHub provided `noreply` address. You can [even block pushes of commits with private mails](https://help.github.com/en/articles/blocking-command-line-pushes-that-expose-your-personal-email-address).

So far just the possibilities. I just wanted to serve this as a friendly reminder, so you don't notice this only when it's too late. What you'll do depends solely on you. :smile:

**Comment by hogren** [comment]
@rugk  thank you for your advices ! I change that. I will send another PR with the new conf :)
@elrido look my next PR and tell me if it's correct

**Comment by rugk** [comment]
BTW there should actually no need to create a new PR, just `git push --force` and it overwrites old changes/commits.

**Comment by hogren** [comment]
See #756

**Pull request closed without merging**
