### PR TITLE
#479 Enhance URL shortener integration, clear address bar and discussion when create new paste from existing paste

### PR DESCRIPTION
**Pull request by Haocen**
…

This PR fixes 
https://github.com/PrivateBin/PrivateBin/issues/479
https://github.com/PrivateBin/PrivateBin/issues/484
https://github.com/PrivateBin/PrivateBin/issues/354
## Changes

1. The address bar is not cleared when creating new paste from existing paste. This is fixed.
2. The URL shortener integration is poor, it is enhanced.
3. The discussion is not cleared when new/clone paste is clicked.

## ToDo

* [ ] 
* [ ] 
* [ ]

### CODE REVIEW

**Comment by Haocen** [comment]
Would appreciate any feedback, review will be addressed in timely manner.

Feel free to contact if no response on GitHub https://haocen.dev/#contact , PR TTL: 30 days.

**Comment by elrido** [comment]
I don't mind the change and can take a closer look and test it over the weekend. @rugk & @r4sas , what are your thoughts?

**Comment by r4sas** [comment]
Never used URL shortener, so I have nothing to say about it. Discussion and URL cleaning will check on weekend.

**Comment by elrido** [comment]
It works with yourls as well.

**Pull request merged**
