### PR TITLE
Add Shiftleft scan

### PR DESCRIPTION
**Pull request by rugk**
It seems [to cover](https://slscan.io/en/latest/#supported-languages-frameworks) PHP including license check in addition to dependency scanning.

Ref https://github.com/PrivateBin/PrivateBin/issues/504 and https://github.com/PrivateBin/PrivateBin/issues/741

### CODE REVIEW

**Comment by elrido** [comment]
Tainted file handling: I think they detect that there is a code path that extracts the paste ID as a file name from the $_GET parameters and finally might unlink (delete) that file. This is potentially dangerous, if this path allows arbitrary file names (say, `/etc/passwd` and the app happens to have the permissions to delete it. In our case we [validate the ID](https://github.com/PrivateBin/PrivateBin/blob/a2ffbafa136fb8db83e956c2a63f4974f9f6103f/lib/Model/AbstractModel.php#L159), so it should be safe. Other ways of doing this would be to look up the given user input in a database, acting as an opto-coupler that isolates two electric circuits.

I did go through the list and marked the (to me) obvious false positives or test cases (we do for example use an encrypted paste and it's secret hash and password in the unit tests to validate older formats can still be decrypted). Could you validate the others and let us know of any that need to be discussed further?

I did address the one about the float 0.0 to string comparison. The "Redundant cast" could be solved with type declaration, but `string` is AFAIK only supported as of PHP 7.0, so adding that would break 5.6 compatibility, just to please a reporting function. I do like explicit type declaration as a feature very much, don't get me wrong, and look forward to adding it for all our ints and strings, once we drop 5.6 support due to necessity.

**Comment by rugk** [comment]
Great, thanks for doing so.

> I do like explicit type declaration as a feature very much, don't get me wrong, and look forward to adding it for all our ints and strings, once we drop 5.6 support due to necessity.

Do we already have an issue for that?
If not, we should create one and plan when we want to do that. Also let's not forget to note that we should adjust the line it reported there…

As for the file handling: Yep, sure, that's fine in our case.

**Comment by rugk** [comment]
So AFAIK you've tackled all of them. We can close the tainted file handling if we can verify/assure the validation works… I dunno how. Does someone wants to dive into the code again?

**Comment by elrido** [comment]
According to our code coverage report, there are 79 tests exercising that line in our unit tests:
https://privatebin.info/coverage/Model/AbstractModel.php.html#159

**Comment by rugk** [comment]
> once we drop 5.6 support due to necessity.

ping @elrido  just letting you know AFAIK we've dropped that in #707

**Review by elrido — APPROVED** [review]
Let's give it a try

**Pull request merged**
