### PR TITLE
Update jQuery 1.11.3 ==> 3.1.1

### LINKED ISSUE #115: jQuery outdated?
The version jQuery uses on PrivateBin is 1.11.3, But the latest jQuery version is 3.1.1, should PrivateBin update to the latest?

### PR DESCRIPTION
**Pull request by nolsen42**
* [X] I agree to release the changes in this PR under the Zlib/libpng license as shown in the  [LICENSE file](https://github.com/PrivateBin/PrivateBin/blob/master/LICENSE.md#zliblibpng-license-for-privatebin).

Fixes #115 

This PR updates jQuery from 1.11.3 to 3.1.1

## Changes

* Update jQuery 1.11.3 ==> 3.1.1

### CODE REVIEW

**Comment by rugk** [comment]
Thanks for your PR. First I've edited your PR description, to [let the issue automatically close](https://help.github.com/articles/closing-issues-via-commit-messages/) when a PR is merged.

Also as a general suggestion for git/GitHub: You might want to make all changes you want to submit to other projects in a separate branch.

As for this PR, I'll look at this later. Todo:
* [ ] Verify jQuery script/hash
* [ ] Verify that everything works
* [ ] research whether it could have negative consequences ([doc](https://jquery.com/upgrade-guide/3.0/)) - browser compatibility, ...?)

**Comment by rugk** [comment]
If you want to do the 3rd point (see [this doc](https://jquery.com/upgrade-guide/3.0/#jquery-migrate-plugin)) you could help us very much.

**Comment by nolsen42** [comment]
I wonder does the compressed version of jQuery have any improvements in page loading times (Because jQuery can be a bit slow)

**Comment by rugk** [comment]
Ah, yes. Please use the minified jQuery version. It saves a few bytes when downloading it.

**Comment by nolsen42** [comment]
@rugk According to pingdom, there is a 94ms decrease in load time, when comparing to the original code and the minimal 3.1.1 jQuery.

**Comment by Wikinaut** [comment]
(I would always suggest to use the latest jQuery code)

**Comment by Wikinaut** [comment]
(I was following and using zerobin for a very very long time and migrated today to privatebin and will actively support this great project)

**Comment by nolsen42** [comment]
I'm going to look into resolving those issues pingdom brings up, to reduce load times.

**Comment by rugk** [comment]
```
$ cat jquery-3.1.1.min.js | openssl dgst -sha512 -binary | openssl enc -base64
U6K1YLIFUWcvuw5ucmMtT9HH4t0uz3M366qrF5y4vnyH6dgDzndlcGvH/Lz5k8NF
h80SN95aJ5rqGZEdaQZ7ZQ==

Correct hash in PR #117 by @nolsen42.
-----BEGIN PGP MESSAGE-----

owEBBwP4/JANAwAKAQXUCmNq+rNNAcvAFmIAWA+z9CQgY2F0IGpxdWVyeS0zLjEu
MS5taW4uanMgfCBvcGVuc3NsIGRnc3QgLXNoYTUxMiAtYmluYXJ5IHwgb3BlbnNz
bCBlbmMgLWJhc2U2NApVNksxWUxJRlVXY3Z1dzV1Y21NdFQ5SEg0dDB1ejNNMzY2
cXJGNXk0dm55SDZkZ0R6bmRsY0d2SC9MejVrOE5GCmg4MFNOOTVhSjVycUdaRWRh
UVo3WlE9PQoKQ29ycmVjdCBoYXNoIGluIFBSICMxMTcgYnkgQG5vbHNlbjQyLgqJ
AhwEAAEKAAYFAlgPs/QACgkQBdQKY2r6s00XGxAAjuNIaZ9ZNeuR9VJ2eZxSZG7w
C4V6YbcJp9czKEltgwCwwYth3n7vtwsy/ym3HCBd9GR97yNLzwSCzZDjmDGCShhN
D3jiOINfNjE5iP17L/aHMfArw/6re+waOrcOkYrJHUCZAl9Izd7h2yb7Cs2+0Doi
3QogZg6fHbZ3XspKbRjbRQrLAhl4usGhHb0ujVoI98oseItHYerkXOl919uB7YhY
xwkzRe82H9i0pVJFJCtNjujpCcPhIPt1u1ajnsR2hsX7UyPsQh2AENckXcxgU5aF
ASC6wh3Drza4/2Sj2jo3D/kLuqGzYRxmERjgQPjVG2l8INIiw88XybwZ6uriqL/x
usBBqzYaRkwevDSvbh8gaYka4xhFDy76IIxp0d9GZA/XmxpYZi1g68MBqrxD/KEO
Vg8MFYrdUQgjMP33BpkizCav7rL58B+WO+Bieq+RaxnH2qwSRM9+i73tW86/0Hnw
6n2wsx8PqigcVrUE8HHjCoZKn59mQIETxMW4mqdfhbkGSIRn4qKTtkAipWcJ3AI9
HwdlG46S+p3QGqpV79spssYB7keeT04NvuQpoSucjB5rfuo5n3ION6sgUXZW7c0C
h5xUwsJqk7AA1ZQ7Q8OlR+EPmVQ46U0lDA0F8GjVpZ8+fZIjc05O6MurywVjK4gg
2mX9MQiEioF6GZf1WPc=
=yeUY
-----END PGP MESSAGE-----
```

**Comment by elrido** [comment]
Thanks for submitting this.

We use jQuery mostly for easier DOM access and to handle AJAX cross browser. Had deliberately avoided upgrading as the upgrade notes gave me the impression the AJAX handling had significantly changed. Will try to do an in-depth test of this over the coming weekend (we still have no JS unit tests :-( ).

**Comment by elrido** [comment]
Could not find any JS issues. Really glad, as I had feared that the AJAX changes would interfere with our usage of them.

Thanks again for preparing all this!

**Pull request merged**
