### PR TITLE
Added Spanish Translation

### PR DESCRIPTION
**Pull request by Ahuahuachi**
## Changes

* Added translation file es.json 
* Modified privatebin.js to show new supported language

### CODE REVIEW

**Comment by Ahuahuachi** [comment]
# Possible bug
While testing out the Spanish translation, I noted that the strings of confirmation are not being translated. ("Your paste is..." and "Delete data")
This only occurs with this specific translation, but could not get to the solution.
image

**Comment by elrido** [comment]
Thank you very much for the Spanish translations!

As I could not reproduce the error, I suspect that it was due to your browser still having cached the JS from before the change and therefore falling back to English for that message (the other texts were translated server side).

**Comment by Ahuahuachi** [comment]
Thank you for maintaining this project. It's just my little contribution as I was big fan of Zerobin.

Maybe it was an issue with the installation. Cleaned browser cache, used two more different browsers in normal and "incognito" mode but it always fell to English until I reinstalled the master branch.

**Comment by Ahuahuachi** [comment]
Thanks @tmelikoff for the heads up. I just proposed a pr to fix this. #190

**Pull request merged**
