### PR TITLE
Default to en if browser does not provide a language

### LINKED ISSUE #296: Unable to load when browser has no preferred language defined
## Steps to reproduce
Tested with Firefox
1. Remove all preferred languages : Options > Languages > Choose your preferred language for displaying pages
2. The list is empty. Now you can go to https://privatebin.net

### What happens
You are not able to load the webpage. You follow the [FAQ to troubleshoot](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-not-the-loading-message-go-away) but this doesn't help.

The console shows the messages about `loadTranslations`

### What should happen
The page should load with a default language.

I can reproduce this issue on <https://privatebin.net>: Yes

### PR DESCRIPTION
**Pull request by otaku**
This PR fixes #296

If the language from the browser can not be detected, I've set the default language to "en".

### CODE REVIEW

**Comment by rugk** [comment]
Also I am not so much into the unit test, but line
```js
$.PrivateBin.I18n.reset('en');
```

already resets the language to English, so it would not even try to translate it to any other language? So does the test really fail, if your change is not included?

/cc @elrido

**Comment by otaku** [comment]
The test worked as I wrote it but forgot to commit it.

The issue lies with ```(navigator.language || navigator.userLanguage)```  ```navigator.language``` is an empty string and ```navigator.userLanguage``` is undefined for me when I remove all languages.  

```('' || undefined)```  results in ```undefined``` which is not a string object and throws an error.

**Comment by rugk** [comment]
Ah, ugh, okay. So the test is even broken, okay. So would be nice if you could do a follow-up PR.

**Comment by otaku** [comment]
Test is not broken.  It's a working test.  I've simulated missing ```navigator.language``` and ```navigator.userLanguage``` and it not throwing.

**Comment by rugk** [comment]
Ah when `navigator.userLanguage` is undefined, now I get it. Thanks for that explanation.

**Pull request merged**
