### PR TITLE
[i18n] Update en strings

### PR DESCRIPTION
**Pull request by r4sas**
Add plurals for `Please wait %d seconds between each post` and fix translable strings in `This document will expire in` message (add dot at end).

### CODE REVIEW

**Comment by elrido** [comment]
I guess I had simply never considered that anyone would configure this to 1 second. But that is indeed a valid configuration and should get translated appropriately. Thanks!

**Comment by Mejans** [comment]
Hello, who can I contact to give the plural formula for Occitan?
It's like French: ‪nplurals=2; plural=(n > 1);

**Comment by elrido** [comment]
Yes, according to the formula from https://localization-guide.readthedocs.io/en/latest/l10n/pluralforms.html it has a single plural.

**Comment by Mejans** [comment]
I made translations on crowdin, I hope I made it properly.

**Comment by elrido** [comment]
Thanks, merged in #705

**Pull request merged**
