### PR TITLE
WIP: Experiment showdown

### PR DESCRIPTION
**Pull request by elrido**
Trying to figure out what CodeQL doesn't like about showdown 2.0.0 - the minified version is all on one line, so it isn't clear what part of the code it complains about.

### CODE REVIEW

**Comment by rugk** [comment]
Yeah, good idea, maybe upstream missed something here and did not properly escape that RegEx?

Resulst are here: https://github.com/PrivateBin/PrivateBin/pull/892/checks?check_run_id=5265013962

It is anyway a good idea to investigate this and, if problematic, report it upstream.

**Comment by rugk** [comment]
Ahhh wtf, it only complains about the minified version?

However, the minifier they use could also be problematic and introduce vulnerable/bad code so... uff...

**Comment by rugk** [comment]
@elrido So what is your result?

**Comment by elrido** [comment]
I think you already saw and mentioned it over in the other topic, but for future reference, I raised an issue with the Showdown project asking for a review of the report.

**Pull request closed without merging**
