### PR TITLE
Use pako instead raw[de/in]flate

### PR DESCRIPTION
**Pull request by r4sas**
This PR fixes https://github.com/PrivateBin/PrivateBin/issues/188#issuecomment-281284360.
Replacing non-RFC rawdeflate/rawinflate libraries to pako library (compatible with RFC and zlib).

## ToDo (if requested):
* add compitablity with old raw[de/in]flate via config

**Edit by @rugk:** Fixes https://github.com/PrivateBin/PrivateBin/issues/260

### CODE REVIEW

**Comment by elrido** [comment]
Thank you very much, this may certainly be a basis for what we can use in a future paste format.

The patch you do here does remove the old library and support for it, which means that it breaks compatibility with any existing installations completely. One key aspect of this project is, that it provides backwards compatibility with previous ZeroBin versions. There are many installations that were upgraded to PrivateBin solely because existing paste can still be opened.

I hope you have my understanding, why we therefore could not merge you pull request in this state. Would you be interested in working with us towards a backward compatible version of the paste format? I would support such an effort and we can manage it in this pull request if you like.

**Comment by r4sas** [comment]
@elrido, so I wrote that on request it will be possible to implement and backward compatibility =)
I will review, how to make compatibility with older versions of ZeroBin/PrivateBin.

**Comment by cryptomilk** [comment]
Nice work!

**Comment by cryptomilk** [comment]
@r4sas Did you just compress some text with rawinflate and try if you can decompress with pako? If this works everything is fine.

**Comment by cryptomilk** [comment]
Ok, it doesn't work. I don't have time to look further. But if you can compress the text "foobar" with pako and with rawinflate and post it, we can compare it. I guess pako is able to decompress it if we tell it how to do it.

**Comment by cryptomilk** [comment]
Try pako.deflateRaw()

**Comment by r4sas** [comment]
@cryptomilk,
> Did you just compress some text with rawinflate and try if you can decompress with pako?

As we [found before](https://github.com/PrivateBin/PrivateBin/issues/188#issuecomment-281284360), it will never be compatible with other versions of zlib.

**Comment by elrido** [comment]
Thanks for this patch. As was discussed in #38 and #28 we need to properly plan a new format of the paste, so that we are not forced to offer hard switches in the configuration to enable/disable compression or compression algorithm.

Here is my proposal for the paste format versions:

**Version 1** - Exactly the same as what was used since Zerobin using the incompatible rawdeflate format, etc.

**Version 2** - Some meta-data is moved into the encrypted data container, which is now no longer just the paste, but another JSON structure to hold the paste, (optional) attachment and attachment name plus any metadata that makes no sense to leave unencrypted. Paste format proposal (using JSON notation):

```
{
    "data": "{"iv":"EN39/wd5Nk8HAiSG2K5AsQ","v":2,"iter":1000,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","salt":"QKN1DBXe5PI","ct":"8hA83xDdXjD7K2qfmw5NdA"}",
    "meta": {
        "postdate": 1344803344,
        "expiredate": 1344803344,
        "burnafterreading": true,
        "opendiscussion": false
    }
}
```
Note the v:2 in the data, indicating its a version 2 paste format and needs to be treated differently. Public metadata:
* "formatter" is moved to the encrypted metadata, as it is only needed for display after successfull decryption.
* "postdate": Needed for comments as these need to be sorted by date on the server side to allow for (future) pagination. Could be useful for sorting of pastes if we ever offer an administration interface. Not really a secret, as the server knows this anyway.
* "expiredate": Required server side to handle expiration of pastes.
* "burnafterreading": Required to allow for deletion without deletetoken / alternative delete behaviour after first access.
* "opendiscussion": Required server side to know if comments are accepted for a given paste or not. When responding it is used to avoid searching for non-existing comments when they are disabled in the paste => faster response.

When decrypted, the data would contain the following JSON string:
```
{
    "paste": "text content of the paste",
    "attachment": "[binary contents of the attachment file]",
    "attachmentname": "filename.ext",
    "meta": {
        "format": "plaintext",
        "compression": "none"
    }
}
```
Encrypted metadata:
* "formatter": same three options as before. A server administrator my decide only to offer plaintext pastes. If someone pastes another format to this server (eg. by using a CLI client), one will not able to view it on that servers web interface.
* compression: May be "none", "dankogai" or "zlib" (and maybe "gzip" and "lzma" in the future?), PrivateBin would use standard compliant zlib as the default, but could still decrypt uncompressed pastes, if we ever switch this default or for simpler CLI clients that want to avoid implementing compression at all. The question here is if we even want to support a "dankogai" option or only use that one in version 1 format?

If the client gets a v1 paste, it falls back to the old way of handling the paste. nodeJS or Rhino based CLI-clients are possible, but due to lack of implementation of the dankogai deflate variant, no other languages will be supported.

v2 pastes will offer the ability to choose compression on or off, using a standardized algorithm. Clients may use all algorithms offered by the pako library (so the web client may still be used to view them) or even skip compression. CLI clients should be doable in most languages/platforms, probably even Powershell :wink:.

**Comment by cryptomilk** [comment]
You can't really put the postdate and experation date into the encrypted metadata. A user could set invalid dates in there and you're not able to verify them.

So the postdate should be set by the server in the database. You can put the expartion time into the metadata, but I don't think it makes much sense. The server should be able to remove expired pastes. If you put this information in the metadata you can only validate them when encrypted and this does only happen on a client.

Also burn after reading is something we need to think about. Should this be enforced by the server or is the client responsilbe. The client can just decrypt it and then do not remove it ...

I think this should be discussed in a ticket and we should create a wiki site with the ideas. I've documented the old format but someone removed it.

**Comment by elrido** [comment]
I did not propose to put post or expiration timestamps in the encrypted part of the paste. This clearly needs to be readable on the server side, hence it stays in the public part of my proposal.

The burnafterreading enforcement is a topic [discussed](https://github.com/PrivateBin/PrivateBin/issues/174) and [changed a few times](https://github.com/elrido/ZeroBin/issues/11). The current consensus seems to be to let the server operator decide his/her use case. On one hand side you don't want to annoy users that mistype the password and then never get to see the paste, on the other hand, the safest is to delete it on the server after first read, which was argued acts as a detection for third parties snooping into your communication, like for example Skype does.

**Comment by rugk** [comment]
I'll certainly change the brunaftereading thing, but that's a future topic. The setting however should be in the encrypted part.

**Comment by elrido** [comment]
If that setting (burnafterreading) is in the encrypted part, how will the server know its such a paste and that it should be deleted?

**Comment by rugk** [comment]
Ah, yes. Of course it needs to be in the plaintext/only authenticated part of the encryption.

**Comment by elrido** [comment]
Good point about the authentication: We could try to move the public metadata into the adata field of the paste and use the encryption JSON directly instead of putting it into a lonely data property.

**Comment by elrido** [comment]
FYI: I have documented some findings on the current and past encryption formats over in the [JS unit testing ticket](https://github.com/PrivateBin/PrivateBin/issues/32#issuecomment-292439392), which might be of interest.

**Comment by r4sas** [comment]
Returning to work with CLI, i want to retort on that change: https://github.com/PrivateBin/PrivateBin/pull/193#issuecomment-285849804.

We mustn't change version flag, because it not affected to cryptography (sjcl) itself, but to privatebin.
That flag must be changed only when we implement new type of crypto.

Otherwise all current implementations of SJCL will not work (https://github.com/berlincode/sjcl/blob/master/sjcl/sjcl.py#L184 as example which I started use now).

**Comment by otaku** [comment]
Just to note the following are are the same:
```js
function compress1(s) {
  return Base64.toBase64(deflate(Base64.utob(s)))
}
function compress2(s) {
  return Base64.toBase64(pako.deflateRaw(s, { to: 'string' }))
}

function decompress1(s) {
  return Base64.btou(inflate(Base64.fromBase64(s)))
}
function decompress2(s) {
  return pako.inflateRaw(Base64.fromBase64(s), { to: 'string' })
}```
I've been able to decompress / compress from Python and Go

**Comment by rugk** [comment]
Maybe theoretically it should be the same but AFAIK actually is not, because the rawdeflate has a bug and compresses not properly. See thread above.
Did you consider that?

**Comment by otaku** [comment]
@rugk It is actually the same.  I can compress with rawdeflate and inflate with pako.  I can also deflate with pako and use rawinflate to uncompress.  There is no bug that I can see.  The above is trying to use gzip compression instead of a deflate stream, which is RFC 1952.  rawdeflate is RFC 1951 however.  pako.deflateRaw and pako.inflateRaw handle RFC 1951.

The issue is with rawinflate / rawdeflate converting the byte array to a string.  That needs to be taken into account when processing in another language.  I have been able to compress / uncompress with both Python and Go.

**Comment by rugk** [comment]
Ah, that sounds great, IMHO. So if you want, you could indeed open a PR.

**Comment by cryptomilk** [comment]
Is pako already used now?

**Comment by elrido** [comment]
No, as explained, this is planned for 1.3 with the big rework of the paste format. I haven't looked into if Webcrypto API includes gzip or just AES support.

**Comment by mikaelhg** [comment]
For completeness, here's a Python PrivateBin downloader using the `python-sjcl` library which looks into the abyss of self-implemented cryptography for us:

```python
PRIVATEBIN_HEADERS = {'X-Requested-With': 'JSONHttpRequest'}

def download_privatebin(url):
    pu = urllib.parse.urlparse(url)
    get_url = f'{pu.scheme}://{pu.netloc}{pu.path}?{pu.query}'
    page = requests.get(get_url, headers=PRIVATEBIN_HEADERS).json()
    msg = SJCL().decrypt(json.loads(page['data']), pu.fragment)
    barr = bytearray(map(ord, base64.b64decode(msg.decode('utf-8')).decode('utf-8')))
    return zlib.decompress(barr, -zlib.MAX_WBITS).decode('utf-8')
```

Don't you just love double-encoded JSON?

**Comment by mqus** [comment]
I'm currently trying to create a downloader for privatebin pastes but I can't seem to get the deflate to work (obviously because of the issues described in #188) . I also tried the python scripts posted above but they don't seem to work. When I use it as-is, python (3.7) complains (`ValueError: byte must be in range(0, 256)`) at the conversion into the bytearray. If I simplify the line to 
```python
barr = bytearray(base64.b64decode(msg.decode('utf-8')))
#or
barr = base64.b64decode(msg.decode('utf-8'))
```
then zlib complains (`zlib.error: Error -3 while decompressing data: invalid block type`)

Where did I go wrong?

**Comment by cryptomilk** [comment]
I don't  have it working either.

**Comment by mqus** [comment]
I finally got it to work, and even in rust (where I originally wanted to implement this). I had to port the btou function of base64 somewhat:
```rust
    pub fn btou(inp:&[u8])->Vec<u8>{
        let mut v=vec![];
        let mut skip=0;
        for i in 0..inp.len(){
            if skip>0{
                skip=-1;
                continue;
            }
            if 0xc0<=inp[i] && inp[i] <= 0xdf
                    && 0x80<=inp[i+1] && inp[i+1] <= 0xbf{
                skip=1;
                let part=&inp[i..i+2];
                let x=((0x1f & cca(part,0))<<6)
                        | (0x3f & cca(part,1));
                push(&mut v,x);
            } else if 0xe0<=inp[i] && inp[i] <= 0xef
                    && 0x80<=inp[i+1] && inp[i+1] <= 0xbf
                    && 0x80<=inp[i+2] && inp[i+2] <= 0xbf{
                skip=2;
                let part=&inp[i..i+3];
                let x=(0x0f & cca(part,0))<<12
                        | (0x3f & cca(part,1)) << 6
                        | (0x3f & cca(part,2));
                push(&mut v,x);

            } else if 0xf0<=inp[i] && inp[i] <= 0xf7
                    && 0x80<=inp[i+1] && inp[i+1] <= 0xbf
                    && 0x80<=inp[i+2] && inp[i+2] <= 0xbf
                    && 0x80<=inp[i+3] && inp[i+3] <= 0xbf{
                skip=3;
                let part=&inp[i..i+4];
                let cp=((0x0f & cca(part,0) as u32)<<12)
                        | ((0x3f & cca(part,1) as u32) << 6)
                        | (0x3f & cca(part,2) as u32);
                let offset=cp - 0x10000;
                push(&mut v,((offset >> 10) + 0xd800) as u16);
                push(&mut v,((offset & 0x3ff) + 0xdc00) as u16);

            } else{
                if inp[i]<128{
                    v.push(inp[i]);
                }
            }
        }
        v
    }

    //charCodeAt
    fn cca(b:&[u8],i:usize)->u16{
        b[i] as u16
    }

    fn push(v:&mut Vec<u8>,x:u16){
        //discard upper bits
        v.push((x&0xff) as u8);
    }
```

It's not pretty but it works (don't ask me how ;) )

The python code has to be changed somewhat:
```python
PRIVATEBIN_HEADERS = {'X-Requested-With': 'JSONHttpRequest'}

def download_privatebin(url):
    pu = urllib.parse.urlparse(url)
    get_url = f'{pu.scheme}://{pu.netloc}{pu.path}?{pu.query}'
    page = requests.get(get_url, headers=PRIVATEBIN_HEADERS).json()
    msg = SJCL().decrypt(json.loads(page['data']), pu.fragment)
    barr = bytearray(map(lambda c:ord(c)&255, base64.b64decode(msg.decode('utf-8')).decode('utf-8')))
    return zlib.decompress(barr, -zlib.MAX_WBITS).decode('utf-8')
```
(replace `ord` with `lambda c:ord(c)&255` to only use the lower bits and making it convertable to bytearray)

**Comment by mqus** [comment]
Correction: I'm an idiot :D
In rust the `btou` function can as simple as in python:
```rust
fn btou(inp:&[u8])->Vec<u8>{
    std::str::from_utf8(inp).unwrap()
    .chars()//convert to utf codepoints
    .map(|i|(i as u32 &0xff) as u8)//only take the lower 8 bits
    .collect()
}
```

**Comment by cryptomilk** [comment]
I did not use python-sjcl but tried to do it sanely with python crpytography. I had it working in the past and then screwed up again. The code is here:

https://git.cryptomilk.org/projects/cpaste.git/tree/cpaste

**Comment by elrido** [comment]
As you may have seen in #431, I ended up using zlib directly via webassembly instead of pako. What convinced me is that the WASM module + JS interface have a much smaller size, so a quicker first page load and it is [faster then pako when benchmarked](https://github.com/ukyo/zlib-wasm-without-emscripten-sample#benchmark). Given it is the reference implementation we should not be at risk of having incompatible output compared to other deflate implementations. I hope you can agree with this choice.

Should we ever get a browser API for de/inflate, we should switch to that of course.

**Comment by r4sas** [comment]
Is that WASM available on all popular browsers? If yes, since which versions?

**Comment by rugk** [comment]
Except of IE [yes](https://caniuse.com/#feat=wasm).

**Comment by elrido** [comment]
It is a good point and I'll add a full compatibility list over in the PR for all the newly used browser features. Just so we can document this in the final release notes as well, if it gets merged to master.

**Comment by r4sas** [comment]
So, maybe I close that PR?

**Comment by elrido** [comment]
I have created the mentioned [compatibility chart](https://github.com/PrivateBin/PrivateBin/pull/431#issuecomment-493129359). As rugk said, IE will be unsupported (we already display a warning) and the other browsers should work if versions from after September 2017 are used.

You may close this PR, if you are Ok with the other solution (I'll probably set up a public test instance this weekend if you want to test it yourself first). I would not be opposed if anyone would like to curate a version 1.2 based release that uses Pako and the version 1 paste format instead.

**Comment by r4sas** [comment]
Okay, lets wait test instance. I think there can be problems with old smartphones (android 4.0.4 and 4.4) with old WebView versions, but they reach end-of-life in support soon (as API level).

**Comment by elrido** [comment]
I did try to use my oldest 4.0 Android tablet with the test instance (see #431 for it-s URL), but found that it can't handle TLS 1.2 that I have as the minimum TLS level on that server. I doubt it will work in any case, as that version of Android was released in 2012, which predates ECMAscript 2015 support, that most browsers introduced in mid to late 2017, by several years. :-(

**Pull request closed without merging**
