### PR TITLE
Whitelist Paste Creation (not reading)

### PR DESCRIPTION
**Pull request by stevenandres**
Made fixes to my whitelist PR suggested by @rugk

### CODE REVIEW

**Comment by rugk** [comment]
You can just push your new changes in your old branch. No need to open a new PR.

BTW: Next time, try to avoid doing a pull request from the master branch, because you can run into problems when you have a "non-clean" master that does not follow this repo here (i.e. "upstream"). [See this article for details](https://help.github.com/en/articles/proposing-changes-to-your-work-with-pull-requests). Anyway, this only applies the next time.

**Comment by stevenandres** [comment]
Thanks for the pointers - I'll get the hang of it. 

> > > That said, note you can have/configure the same ability in your webserver, too. Maybe even more flexible and possibly more securely.

> > You may be thinking of IP restrictions within .htaccess which is what I originally tried. But that would restrict all usage of PasteBin (both creating and reading). Since there are not separate URL directories for create vs paste, .htaccess is a blunt instrument for that. If for example, you would read pastes at example.com/read/092348029384 and create them at example.com/create, then yes I could use .htaccess to control that by IP.

> You'd need to restrict [only POST requests](https://github.com/PrivateBin/PrivateBin/issues/136#issuecomment-261571017).

Nice! That's an excellent tip and I completely overlooked that. If POST is truly only used for creating pastes and no other functions, I could achieve all this within apache (albeit with a poorer user experience error page) and gain all the flexibility of apache's CIDR network handling. Thanks!

I suppose there's no real need for this PR any more, so I'll go ahead and close it.

**Comment by stevenandres** [comment]
Hmm, the `.htaccess` restrictions of POST just generate a generic server error instead of informing the user what actually happened. So I'm going to keep my PR open. I also noticed an issue where I wasn't properly testing for the existence of a `null` whitelist (disabled feature).

**Comment by stevenandres** [comment]
I fixed the issues that StyleCI reported and one other bug. But I can't make sense of why the php-unit tests are failing from Scrutinizer. It reports "no new issues" and when I look at "all" the issues, it shows bugs from years ago. What should I do?

**Comment by rugk** [comment]
Scrutinizer are really just the unit test and they seem to fail. See here for how to run them locally: https://github.com/PrivateBin/PrivateBin/blob/master/tst/README.md

---

Anyway, generally about that feature, what do you think, @elrido?

**Comment by elrido** [comment]
About the feature: As you already pointed out, something like this would best be handled by a webserver configuration. But the way it is implemented, as an option, disabled by default is not a big risk. And I can see that for some users changing the webserver configuration isn't an option available to them. 

Unit tests: I see that travisCI, our main unit testing driver, which also runs the JS unit tests on top of the PHP ones, didn't run at all for this pull request. It's configuration must be broken or something. I'll get that fixed, so we get a proper report on where it fails and then can get that fixed in the code or change the test if need be.

**Comment by Haocen** [comment]
It seemed this can be easily achieved by WAF(web application firewall).
Is your instance behind Cloudflare, nginx envoy or istio?

Implementing access control in application bussiness level make application log hard to read.

To implement similar access control in nginx:
```
geo $bad_ip {
    default 0;
    202.72.213.218 1;
    another_ip 1;
    another_ip 1;
    ...
    ...
}

## location section ##
      location / {
        proxy_pass  http://backend;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
 
        proxy_set_header        Host            pastebin.net;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        if ( $spammers_ip_cidrs = yes ) {
          limit_except GET {
            deny  all;
          }
        }
``

**Comment by r4sas** [comment]
Checking for IP address in CIDR range can be done with similar code:
```php
function ip_in_range( $ip, $range ) {
	if ( strpos( $range, '/' ) == false ) {
		$range .= '/32';
	}
	// $range is in IP/CIDR format eg 127.0.0.1/24
	list( $range, $netmask ) = explode( '/', $range, 2 );
	$range_decimal = ip2long( $range );
	$ip_decimal = ip2long( $ip );
	$wildcard_decimal = pow( 2, ( 32 - $netmask ) ) - 1;
	$netmask_decimal = ~ $wildcard_decimal;
	return ( ( $ip_decimal & $netmask_decimal ) == ( $range_decimal & $netmask_decimal ) );
}
```

Taken from https://gist.github.com/tott/7684443.

**Comment by elrido** [comment]
Yeah, adding support for subnets is a logical next step that will get requested. With #787 (note to self: add a CHANGELOG entry for that one as well) we introduced an IP parsing library, so we can re-use that to cover single IPs as well as subnets and other abbreviated notations for IPv4 & v6 (the projects websites offer IPv6, for example). I can also use the unit code logic from there as example on how to test the different cases.

**Pull request merged**
