### PR TITLE
bootstrap footer improvements

### LINKED ISSUE #1392: fix the footer at the bottom of the screen
## The problem
The footer is always directly unter the text-box. When I have small messages (e.g. passwords) the footer is more dominant than the message.

## The solution
Fix the footer to the bottom of the screen. So the message is more separated and you can see small messages easier.
Maybe it only makes sense to fix the footer on big screens. On small screens like on Smartphones the footer should have a distance to the message. 

I think the best way is to put the footer on the bottom of the screen as default as long as the message is fit to the display area else the footer is fixed (on big screens) OR moves down with an offset to the messagebox.

## Additional context
On the screenshot the footer (red) should move to the green area.

Screenshot_20240827-202345_1_1

### PR DESCRIPTION
**Pull request by elrido**
This PR fixes #1392 and closes #1400 (supersedes it).

## Changes
- remove unused styles (there are no IDs called `preview` or `comments` in either of the bootstrap templates)
- replace margins & paddings with bootstrap utility classes
- apply min. view port height to `placeholder`, `plaintext` & `prettymessage` IDs (in addition to `message`), to move footer to end of view port in all 4 display modes (edit mode + 2 format styles + empty paste placeholder)

## Preview

bootstrap (3) template on small mobile screen:

bootstrap (3) template on small mobile screen with changes

bootstrap 5 template on small mobile screen (dark mode):

bootstrap 5 template on small mobile screen with changes

For reference, this is the current bootstrap (3) template _without changes_ on the same small mobile screen:
bootstrap (3) template on small mobile screen with changes

### CODE REVIEW

**Review by rugk — APPROVED** [review]
LGTM, though I'd like to hear @Ribas160's opinion first.

AFAIK https://github.com/PrivateBin/PrivateBin/pull/1400 does not overflow at the bottom, does it?
I agree though this should be solvable without great JS calculation etc. Just vh pixels or some CSS tricks should hopefully do it.

**Comment by rugk** [comment]
Seeing the reasoning in https://github.com/PrivateBin/PrivateBin/issues/1392#issuecomment-2338497540 maybe 99.9vh or so could easily fix this? Note you can also do [CSS calculations](https://developer.mozilla.org/en-US/docs/Web/CSS/calc) like `calc(100vh - 1px)` or so…

**Comment by Ribas160** [comment]
The reason why this scroll appears is that 100vw is equal to the height of the device screen, but the height available for the content is less because of the browser address bar, and also the height of the address bar is different in different browsers.
@elrido I agree that the solution with JavaScript may be too complicated for such task.
As an alternative solution, I can suggest to use 100dvh (Dynamic Viewport Height), these units were added not very long ago but already are supported by most of the modern browsers, this units use exactly the area that is available for the content. But for this you will have to change html in the same way as in #1400.
Example:
```
.flex-wrapper {
  display: flex;
  min-height: 100dvh;
  flex-direction: column;
  justify-content: space-between;
}
```
```
<div class="flex-wrapper">
  <div class="container">The content</div>
  <div class="footer">The Footer</div>
</div>
```

So, as I see we have 3 ways:
* Add some fixed vh value to the existing content blocks:
Pros: It is a simple solution, does not require html restructuring.
Cons: In some cases footer can be a bit under the scroll or conversely, not too close to the bottom of the page.
* Use flexbox layout and javascript for calculating viewport height:
Pros: Due to the dynamic calculation the footer is always fixed at the bottom and expand when the content is bigger than the screen.
Cons: Due to using the javascript this solution is more difficult than others, require html restructuring.
* Use flexbox layout and dvh points:
Pros: Does not use javascript, the footer is always fixed at the bottom and expand when the content is bigger than the screen.
Cons: Require html restructuring, may be not supported in old browsers.

**Comment by rugk** [comment]
Hmm good pointers! And dvh seems [to be well supported](https://caniuse.com/mdn-css_types_length_viewport_percentage_units_dynamic). Here more explanation: https://dev.to/frehner/css-vh-dvh-lvh-svh-and-vw-units-27k4

An alternative idea may be a container in the middle, which takes the remaining space which [uses a height of `max-content` ](https://developer.mozilla.org/en-US/docs/Web/CSS/max-content), but maybe that does not even work. :sweat:

**Comment by elrido** [comment]
When I tested this solution (which is just an extension of what we already do for the textarea) with the 70%, it only gives a scrollbar on really tiny screens. Mobile browsers tend to hide those anyway.

This solution:
- does not need to change the HTML structure
- does not need to do height calculations
- seems to already work fine for textarea
- also removes some unused classes (dead code) so overall reduces code size instead of increasing it

I do not mind switching to dvh as browsers that don't support it will simply not enlarge these elements, so the tool remains usable (same applies to vh, which is not that much older). We would have to retest on lots of browser layouts and pick a different number, though. We might get away with 75 or 80 dvh instead of 70 vh.

**Comment by Ribas160** [comment]
I think, the right solution depends on goal we have. If we need some simple fix, @elrido I agree with your solution.
But if we want to have a responsive page, I think the solution with changed layout and dvh is the best one, because with this approach footer depends on both the content and the screen size. I updated the pr #1400.

Also I would like to discuss a comments section:

@elrido in your solution the comments section also at the bottom of the page

image

With dvh solution it is under the saved content

image

Bootstrap 5 template example
image


I think if user allows comments, it means that the discussion could be pretty important and it is better to show it on the first screen. But maybe we should add more margin between comments and pasted text.

**Comment by elrido** [comment]
> Also I would like to discuss a comments section:
> 
> @elrido in your solution the comments section also at the bottom of the page
> [...]
> I think if user allows comments, it means that the discussion could be pretty important and it is better to show it on the first screen. But maybe we should add more margin between comments and pasted text.

Indeed, that is a good point! My solution doesn't address that.

Now, I should have maybe RTFM first. I only now found this in the example section of getbootstrap.com: [Sticky footer](https://getbootstrap.com/docs/5.3/examples/sticky-footer/). I'll update this PR shortly, reverting the change to apply the textarea style to all mode divs and instead use this out-of-the-box solution and post updated the screenshots.

**Comment by elrido** [comment]
Ok, here goes with getbootstraps sticky footer solution, previews on bootstrap 5:

bootstrap 5 new paste view

bootstrap 5 discussion view

Also applied their suggestion for the bootstrap (3) template:

bootstrap 3 discussion view

**Comment by Ribas160** [comment]
@elrido on the bootstrap5 template the behavior of the footer looks well, but here is also some points

You set height 100% both for html and body via bootstrap classes. Due to height:100% the content is overflowing html and body tags. This is not a good practice and we should avoid this.

image

To fix this I suggest to remove h-100 class from the html and body tags and use min-height: 100dvh instead. Unfortunately Bootstrap5 does not support dvh (at least I didn't find it in source code), so I suggest to set it manually in styles.
I can't say that using body tag as a flex container is a bad practice, but I personally prefer to avoid this, that why in my solution  I created a container  that changed the html structure a bit.
Anyway, for simplicity I suggest to add style min-height: 100dvh to body tag and remove all styles from html tag.

Also in bootstrap template you fixed footer to the bottom and it causes the content to overlap the footer.

image

I suggest to use the same approach as for bootstrap5 template

**Comment by elrido** [comment]
I undid that breaking change to the soon deprecated b3 template, switched to dvh and fiddled with the sizes to figure out how to avoid overflows on the small screens. While I don't mind if the project description is cut off / has to scrolled to on the small screens, if we do want to preserve it in all cases, I have to introduce a media query and give those types of screens a different, smaller value for the message height. I'm sticking with the h-100, though, as that is the current recommendation of the bootstrap project and I want to have as little customizations that we have to maintain as possible.

**Comment by Ribas160** [comment]
Ok, I don't want to argue too much about the solution. I suggested what I think is the best one, but it is not me who decides what to use.
Anyway, thank you for the discussion because I learned about new css units 🙂

**Comment by elrido** [comment]
@rugk would you have time for a final review on this one?

**Review by rugk — DISMISSED** [review]
Codewise okay. I did not follow the discussion closely, but as it is a visual change I guess what would help most is to have a screenshot/screencast of what is is shown now, otherwise I cannot really judge it…

Feel free to merge if you think it looks fine, I believe in you to not break everything here… :upside_down_face:

**Pull request merged**
