### PR TITLE
Allow to upload bigger files

### PR DESCRIPTION
**Pull request by cryptomilk**
This PR adds PHP configuration to allow uploading bigger files.

### CODE REVIEW

**Comment by elrido** [comment]
A few quick notes to consider for this change:
- For larger uploads, it's required to increase the POST and upload sizes in the PHP configuration, but also needs to be increased it in the webserver (apache, nginx, etc.) configuration as well.
- Note that DBMS are notoriously bad at dealing with large tables / large columns and any best practice guide will recommend not to store large binary blobs in the DB - If you want to use file uploads I would strongly recommend to stick with the file based storage instead. It is very fast and the only reason I had found so far to use the database was when I needed to provide a distributed system (multiple app servers sharing a common storage). You could still do such a case using glusterFS or NFS shares, but databases are more commonly available in those scenarios.
- I had originally added the DB support to this project, but in my experience with production instances over the last 6 years have never needed to actually use it. The largest file based instance I administer currently uses 900 MiBs of disk space, handles about 10k requests per hour at an average CPU load of 0.004 with 200 MiBs of used RAM on a single VM and still offers <25ms response times. I have no comparable numbers for a databased instance, but you may be able to compare this to your environment.

**Comment by rugk** [comment]
Any news, @cryptomilk?

**Comment by elrido** [comment]
The planned 1.3.1 bugfix release would be a good opportunity to add this to the [database migrations](https://github.com/PrivateBin/PrivateBin/blob/master/lib/Data/Database.php#L711), so this gets fixed automatically. Just need a case for '1.3.1' to be added with the relevant `ALTER TABLE` statements.

**Comment by elrido** [comment]
Since we had no feedback from @cryptomilk and I didn't want to let the opportunity pass, I did the two changes for him: automatic DB upgrade to MEDIUMBLOB and changed the default sizelimit to 10 MiB (wiki page also updated).

**Comment by cryptomilk** [comment]
I'm still on vacation with limted internet access, will be back next week.

**Pull request merged**
