### PR TITLE
Restructure documentation

### LINKED ISSUE #1061: Restructure doc folder
Via discussion with @rugk on another channel:

> > [...] we already store docs like the INSTALL.md in (git) tree. And we have a "doc" folder which is used to generate the source code docs into. How about:
> > - using the "doc" folder for, well, documentation, so move things like INSTALL.md into it
> > - keeping these as markdown format (.md suffix), like now, so they are readable in the github web UI as well as on the CLI (also the wiki content is already markdown)
> > - CHANGE: rename them to their (English) title in natural casing and with spaces? i.e. rename the existing README.md in there to "Generating Source Code Documentation.md". It would make them more discoverable to end users, I think.

> Would not recommend for this particular file as GitHub would not render it when you view only the folder then.

Good point, so maybe rename it, but create a new README.md with links to all the docs and maybe teaser texts. Maybe also links to some selected wiki articles?

In general, we would then open up the doc folder as an area to migrate important documentation from the wiki into, and therefore being able to offer a higher quality of that content, as changes to these will get peer reviewed via the pull request process.

### PR DESCRIPTION
**Pull request by elrido**
This PR closes #1061

## Changes
* moved INSTALL.md => doc/Installation.md
* renamed doc/{README.md => Generating Source Code Documentation.md}
* added a new documentation index doc/README.md
* unified title formats

## ToDo
* [ ] Should we migrate some of the docs we link to in the main README.md from the wiki to the docs as well?
    * FAQ - this has been extended by third parties in the wiki, but some of our source code does rely on the links to some items to keep working
    * Configuration guide - this changes when we add new options, so it would make sense to store it with the source code
    * Templates - changes rarely, but would need to store the screenshots somewhere if migrated, i.e. privatebin.info?
    * Developer guide - ???
* [ ] Should some of the other *.md documents in the root folder be moved as well? I assume some of these have to stay for github functionality to work (license, CoC, security).

### CODE REVIEW

**Comment by rugk** [comment]
> Should some of the other *.md documents in the root folder be moved as well? I assume some of these have to stay for github functionality to work (license, CoC, security).

You would keep that as it is.

> Should we migrate some of the docs we link to in the main README.md from the wiki to the docs as well? 

Due to discussions here in https://github.com/PrivateBin/PrivateBin/issues/1061 that may be useful, but I actually dunno…

**Comment by elrido** [comment]
Ok, then shall we merge this as is to serve as a starting point? We can then add documents over time if we feel it makes sense.

**Comment by elrido** [comment]
ping @rugk - Ok to merge as is (please approve) or do you want me to change anything?

**Comment by elrido** [comment]
ping @rugk - approval, please?

**Review by rugk — APPROVED** [review]
Sorry and if I miss that no problem @r4sas you can also review this even if I am being pined :wink:

**Review by elrido — COMMENTED** [review]
Nope, as the author I can't approve my own PR. :-)

**Pull request merged**
