### PR TITLE
Add Snyk security scan for PHP

### PR DESCRIPTION
**Pull request by rugk**
After I found https://github.com/PrivateBin/docker-nginx-fpm-alpine/pull/44 I saw they also support PHP, so let's do it here (one level before container packaging), too.
Also it complements the CodeQL analysis, which only covers the JS part.

I added the API token to the PrivateBin org now.

Ref https://github.com/PrivateBin/PrivateBin/issues/504 and https://github.com/PrivateBin/PrivateBin/issues/741

### CODE REVIEW

**Comment by rugk** [comment]
Okay so here is the essential part:
```
/usr/bin/docker run --name snyksnykphp_2ae050 --label 8a33c1 --workdir /github/workspace --rm -e SNYK_TOKEN -e INPUT_ARGS -e INPUT_COMMAND -e INPUT_JSON -e SNYK_INTEGRATION_NAME -e SNYK_INTEGRATION_VERSION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/PrivateBin/PrivateBin":"/github/workspace" snyk/snyk:php  "snyk" "test" "--sarif-file-output=snyk.sarif"

Testing /github/workspace...

Organization:      rugk
Package manager:   composer
Target file:       composer.lock
Project name:      privatebin/privatebin
Open source:       no
Project path:      /github/workspace
Licenses:          enabled

✓ Tested 4 dependencies for known issues, no vulnerable paths found.

Tip: Detected multiple supported manifests (1), use --all-projects to scan all of them at once.
```

Seems it just(?) checks the `composer.lock` for vulnerabilities… well, fair enough.

However, do we now need to run `composer` to install optional dependencies, because of the last PR in https://github.com/PrivateBin/PrivateBin/pull/795, which added some big dependencies?

**Comment by elrido** [comment]
> `Organization:      rugk`
> `[...]`
> `Open source:       no`

I suspect that has to do with the account type that you/your organization has on snyk. When I tried to sign up it asked me for the purpose of the account and one of the options referred to using it for an open source project. I got the impression that their service is not free by default, only a trial and one would have to apply for an open source license. If this works out, please try to convert the account or set up a privatebin org and send me an invite, so I can join it as well.

**Comment by rugk** [comment]
Hmm no, I see no way to do it. I can send you a referrer linnk (???), but apart from that… I have no idea. :laughing: 

I had to use OAuth to login, which is ugly and as said chose GitHub.

> When I tried to sign up it asked me for the purpose of the account and one of the options referred to using it for an open source project.

No such thing happened for me. :thinking: 
Maybe it's better if you sign-up if you can do this? :thinking: 

>  I got the impression that their service is not free by default, only a trial and one would have to apply for an open source license. 

Well… I have a big "start free trail button" in the UI, but did not enabled that – and it works – so maybe we don't even use/need their paid features.

---

Ah okay, just need to create a new org. Okay did so. Please tell me what mail you use there (or what I should enter), so I can "invite" you to that project.
Ah and [to get a token](https://github.com/snyk/actions#getting-your-snyk-token) for a org I go [to the settings](https://app.snyk.io/org/privatebin/manage/settings), and then you get [to a page for service accounts](https://app.snyk.io/org/privatebin/manage/service-accounts), which tells you you cannot do this with your plan.
So I guess yes, maybe one has to apply there if one wants an org API key and not use my personal one. :see_no_evil: 
(I hardly care though, but it would be nice, yes.)

**Comment by elrido** [comment]
Thank you for looking into and documenting this!

> Ah okay, just need to create a new org. Okay did so. Please tell me what mail you use there (or what I should enter), so I can "invite" you to that project.

I, too, signed up with my github account - it's probably the email I use for my commits.

**Comment by rugk** [comment]
Okay, invited you. Feel freee to try to get a way to mark the org as a FLOSS project and get our plan upgraded there. :upside_down_face:

**Pull request merged**
