### PR TITLE
Fix #443

### LINKED ISSUE #443: bootstrap-compact template broken on dropdowns
## Steps to reproduce
1. set `template = "bootstrap-compact"` in config
2. change paste expiration

### What happens

expiration is **also** set on formatter dropdown which result in an invalid data post 

## Additional information

This comes from f25661beda3f88a11c9eb8015af77a12d52f8830 which put the `id="formatter"` on the `li` containing the dropdown instead of puttin this id on the `a class="dropdown-toggle"` as it's done for the `expiration` dropdown.

So, the privatebin script doesn't find the right element here https://github.com/PrivateBin/PrivateBin/blob/master/js/privatebin.js#L3807

I can provide a PR movin the `id="formatter"` on the `a` which fix the bug :)

### PR DESCRIPTION
**Pull request by brunob**
fix expiration/formater dropdown with bootstrap-compact template

### CODE REVIEW

**Comment by rugk** [comment]
You can (automatically) [let issues close](https://help.github.com/articles/closing-issues-via-commit-messages/) when a PR is merged if you include the string _in the PR body_, not the PR title.

**Comment by brunob** [comment]
@rugk thx for the welcome message :)

The merge will close the issue since i've used the fix keyword ine the commit message as i often do cf https://github.com/brunob/leaflet.fullscreen/commit/699b9801be93b4a7ecc294014b13bf458f636925

**Comment by rugk** [comment]
Yes, but only closed because the commit contains the "fixes XY". You'll see the difference later. but well yeah… that does not matter. :smile:

**Comment by elrido** [comment]
I'll merge it after the #407 one (as I am currently on that branch and want to avoid having to deal with too many merges/conflicts due to switching back and forth) but should get done this weekend.

**Pull request merged**
