### PR TITLE
Add upload test results job

### PR DESCRIPTION
**Pull request by rugk**
As per https://github.com/marketplace/actions/publish-test-results#use-with-matrix-strategy only one job should upload all results.

### CODE REVIEW

**Comment by rugk** [comment]
> The reason is that workflow_run events only execute workflows from master, so you first have to commit the PR (https://github.com/PrivateBin/PrivateBin/pull/1303) to master for it to get triggered.

https://github.com/EnricoMi/publish-unit-test-result-action/issues/597#issuecomment-2094860394

Okay hmm, so we have to merge it first to test it? Kinda suboptimal, but well…

**Review by elrido — APPROVED** [review]
I'm personally still on the fence regarding if your CI-workflows should be integrated to your repo or live in a separate one. Yes, it's convenient if it's all in one, but it makes testing complex or impossible, especially when some of the triggers depend on branch names or other things that wouldn't trigger on a PR / branch.

It is what it is. Thank you for trying to improve this!

**Comment by rugk** [comment]
Hmm how would you split it? GitHub Actions is all made for living in the same repo.
Also (fortunately), it's not as if we would need to reuse some stuff in multiple repos etc.

**Comment by rugk** [comment]
But okay, I'll merge it and we'll see how it turns out…

**Pull request merged**
