### PR TITLE
make feature detection more robust, let users with no WASM create pastes

### LINKED ISSUE #454: 1.3 doesn't work in browsers that don't support webassembly
## Steps to reproduce

1. Open instance with version 1.3  in TorBrowser e.g. https://snip.dssr.ch/

### What happens
You won't see an editor or content

### What should happen
You should see editor/content

## Additional information
Screenshot from 2019-07-10 10-21-09

## Basic information

**Server address**:  https://snip.dssr.ch/

**Browser:** TorBrowser 8.5.4 (based on Mozilla Firefox 60.8.0esr) (64-bit)

**PrivateBin version:** 1.3

I can reproduce this issue on <https://privatebin.net>: Yes

Maybe related to #441?

### PR DESCRIPTION
**Pull request by elrido**
This PR fixes #454

As [discussed](https://github.com/PrivateBin/PrivateBin/issues/454#issuecomment-511177305), we want to make sure that the feature detection works properly, even when WASM support or the Webcrypto API are missing (i.e. due to non-secure context in Chrome).

Currently still a work in progress, current state can be reviewed at http://zerobin-test.dssr.ch/

## Changes
* Move attempted load of zlib (which requires WASM support) behind feature detection (into its end, actually)
* Made zlib lazy loading instead of awaiting it in initialization, if it fails, creation switches to uncompressed mode, but decryption still triggers a warning message.
* Since I needed a warning and not a status or error message, I finished implementing this Alert type, which already was partially supported. Basically it shows as an error message, but with different icon.
* Used this new warning in a few places we previously had errors.
* Noticed that we double translate some of the errors (the Alert classes methods automatically translate) and fixed this.
* Due to switching to a different IDE plugin, I noticed a few cases of unused variables and removed them as well.

## ToDo
* [x] Insecure context in Chrome currently triggers the warning, but not yet the error about unsupported Webcrypto API.
* [x] Need as many folks with different browsers as possible to test if this fixes the various cases.
* [x] Handle any cases that this has missed.

### CODE REVIEW

**Comment by rugk** [comment]
I don't know whether it's ready yet, but I've tested this in Edge and it does not seem to work...

grafik

**Comment by rugk** [comment]
> IDE plugin

BTW, which one?

**Comment by elrido** [comment]
It is still WIP and not ready for testing ATM - I'll post an update in this thread when I need more eyeballs on it.

Edge will not be supported (due to its [lack of SHA256 support in webcrypto](https://github.com/PrivateBin/PrivateBin/issues/468#issuecomment-516397909)), until the switch to the Chromium engine, but you will get an appropriate error message, if we implement the feature detection correctly.

**Comment by elrido** [comment]
Sorry, I missed to answer this one:

> > Due to switching to a different IDE plugin, I noticed a few cases of unused variables and removed them as well.
> BTW, which one?

I am using Eclipse IDE (currently 2019-06) with the web developer tools since many years for PHP and JS projects. Since I started using async/await the JS view to stops the validation halfway through privatebin.js and only offering syntax highlighting and other small improvements over a pure text editor. Researching a bit further I realized that they currently only support ES6, which doesn't cover this feature and it seems quite a challenge to implement in the current viewer for JS. I now discovered the [Wild Web Developer project](https://projects.eclipse.org/projects/tools.wildwebdeveloper) that adds a lot of these more recent developments into the default text viewer (more [details on why Eclipse is lacking on that front can be found in the proposal](https://projects.eclipse.org/proposals/eclipse-wild-web-developer) for the Wild Web Developer project to the foundation).

Sorry for the OT, next update will be on the status of this branch, probably during the coming weekend.

**Comment by elrido** [comment]
Ok, so with the current state we have ([test server](http://zerobin-test.dssr.ch/) got updated):
- the error message with link to redirect to https for browsers that don't have Webcrypto in insecure contexts (*cough* Chrome *cough*)
- a warning message when the browser doesn't support webassembly, but let's you create an uncompressed paste
- ensured that both browsers with and without webassemby support can read uncompressed pastes
- while testing the password functionality, I found and addressed the retry option not being offered - fixes #469

Specifically, the following cases got tested:
- browser with WASM support (Firefox 68.0.2)
  - creates paste with zlib compression, no password
  - creates paste with zlib compression, with password
  - reads paste with zlib compression, no password
  - reads paste with zlib compression, with password + retry button works
  - reads paste without compression, no password
  - reads paste without compression, with password + retry button works
- browser without WASM support (Chromium 76.0.3809.100, started via `chromium-browser --js-flags=--noexpose_wasm`)
  - creates paste without compression, no password, but shows WASM warning
  - creates paste without compression, with password, but shows WASM warning
  - fails to read paste with zlib compression, no password + shows WASM error
  - fails to read paste with zlib compression, with password + shows WASM error
  - reads paste without compression, no password
  - reads paste without compression, with password + retry button works

Final To-Do, before I would consider to remove the WIP:
- [ ] move the `InitialCheck` class sideways into a `legacy.js` that restricts itself to traditional JS to ensure IE et al can display the relevant errors

**Comment by elrido** [comment]
Legacy checks got split out and I did my best to make it IE 11 proof using the browserling website, but reached their free tier limit before . I did apply for a free account at BrowserStack as I no longer have access to a paid account with them. That would let me do more tests, ideally even older IE and Safari versions or mobile browser.

It won't let me do tests with Tor browser or i2p, so @ any folks with those, please review and report the status with these on the [test site](http://zerobin-test.dssr.ch/).

I am happy with the state of this branch on Firefox and Chrome and so remove the WIP. Please review and let me know of any glitches that I can still address in this merge request. I intend to relatively soon release a 1.3.1 once we can (agree to) merge this into master.

**Comment by elrido** [comment]
I got a bit more testing with browserstack done and here are some results:
- WinXP / IE 6, 7 & 8 - fails with errors loading jQuery, legacy.js is a jQuery module, doesn't display modern browser warning, just the JS loading message
- WinXP / Safari 5.1 - fails with '$.PrivateBin.Alert is not an object', doesn't display modern browser warning, just the JS loading message
- WinXP / Opera 36 - no console, displays the insecure connection warning and the JS loading message, doesn't display modern browser warning
- WinXP / Chrome 49 - 'unexpected token function' in privatebin.js, pointing to async function, displays the insecure connection warning and the JS loading message, doesn't display modern browser warning
- WinXP / Firefox 52 - fully works, displays the insecure connection warning on HTTP
- iPhone XS - fully works, displays the insecure connection warning on HTTP
- Samsung Galaxy S9 - HTTP doesn't work, displays no errors or loading message / HTTPS fully works
- MacOS / Chrome 77 - HTTP doesn't work, displays no errors or loading message / HTTPS fully works
- MacOS / Safari 12.1 - fully works

I definitely want to explore why HTTP on Chrome 77 fails to even display errors and fix that. Browsers that fail to parse privatebin.js could be made to display the errors if I move the Alert classes into the legacy.js *or* I use a simpler replacement that doesn't translate and just removes the hidden class of the error message. The really old IEs fail due to lack of support by jQuery, which surprises me a bit. I may try to make just the legacy.js work without jQuery, if I still find time to do so before the weekend.

**Comment by elrido** [comment]
Made a bit of progress and HTTP mode now shows the correct warnings in Chrome and Android and IE 11. I may still spend a bit of time to play with removing jQuery dependencies in legacy.js before merging this on the weekend. It is only used for simple DOM element selection and as a namespace for the classes.

Updated testing results:
- WinXP / IE 6, 7 & 8 - fails with errors loading jQuery, legacy.js is a jQuery module, doesn't display modern browser warning, just the JS loading message
- Win10 / IE 11 - HTTP doesn't work, displays try HTTPS error and modern browser warning / HTTPS  doesn't work, displays modern browser warning
- WinXP / Opera 36 - no console, displays the insecure connection warning and the JS loading message, doesn't display modern browser warning
- WinXP / Chrome 49 - 'unexpected token function' in privatebin.js, pointing to async function, displays the insecure connection warning and the JS loading message, doesn't display modern browser warning
- WinXP / Firefox 52 - fully works, displays the insecure connection warning on HTTP
- iPhone XS - fully works, displays the insecure connection warning on HTTP
- Samsung Galaxy S9 - HTTP doesn't work, displays try HTTPS error and modern browser warning / HTTPS fully works
- Win10 / Safari 5.1 - fails with with errors loading jQuery, legacy.js is a jQuery module, doesn't display modern browser warning, just the JS loading message
- Win10 / Chrome 77 - HTTP doesn't work, displays try HTTPS error and modern browser warning / HTTPS fully works
- MacOS / Safari 12.1 - fully works

**Comment by elrido** [comment]
With the latest changes I removed the jQuery dependency from legacy.js, which made it work on IE 6 - 11 and did introduce a async/await and ES6 arrow function feature detection, so that old Chrome and Opera builds with webcryto, but lacking ES6 and async support get the "modern browser" error displayed.

I'm happy now and will soon merge this.

**Pull request merged**
