### PR TITLE
Clever gitignore for vendor dir

### PR DESCRIPTION
**Pull request by rugk**
* [x] To the extent possible under law, I have waived all copyright and related or neighboring rights to this PR and publish it as public domain.

This PR fixes the discussion in https://github.com/PrivateBin/PrivateBin/pull/65#issuecomment-239751734 (it's a try, at least)

## Changes

* Ignore vendor dir only partially, allows all PHP files
* This results in the Composer license file being ignored, so I added it to the general license
* Removed some other unnecessary files, which had something to do with composer
* I explicitly needed to exclude the license files, theoretically we could also explicitly include them, so that we do not need to add them to the general license file.
* Additionally I also excluded test directories. This list can be expanded further.

### CODE REVIEW

**Comment by rugk** [comment]
Example of files, which would be included:

```
	vendor/EXAMPLE.php
	vendor/composer/autoload_files.php
	vendor/paragonie/EXAMPLE.php
	vendor/paragonie/random_compat/lib/EXAMPLE.php
	vendor/paragonie/random_compat/other/
	vendor/yzalis/EXAMPLE.php
	vendor/yzalis/identicon/EXAMPLE.php
	vendor/yzalis/identicon/src/EXAMPLE.php
	vendor/yzalis/identicon/src/autoload.php
```

**Comment by rugk** [comment]
TravisCI failure is only a broken test in TrafficLimiterTest. These tests seem to be quite unstable...
At least there is nothing wrong with this PR.

**Comment by elrido** [comment]
Thank you for the cleanup!

One thing: The doc/ folder in my dev environment contains all the generated API docs from phpdoc, similarly to the tst/log/ after running phpunit. Could you revert just that one ignore rule?

**Comment by rugk** [comment]
Mhh, but our own doc should be included, so I'll try to generate the doc to see how to exclude it in a nice way. Maybe only include Markdown files?

**Comment by rugk** [comment]
Or well, we could of course also just change this command suggested there: `phpdoc -d lib/ -t doc/`

**Comment by elrido** [comment]
Thanks!

**Pull request merged**
