### PR TITLE
[WIP] Add "JS not working" error message

### LINKED ISSUE #103: Add "JS not working" error message
After https://github.com/PrivateBin/PrivateBin/issues/100 I think it is a good idea to add an error message:
- which is _not_ shown when no JS is supported (so it must be hidden)
- which is shown when JS could not load correctly (is not executed (so there might just be a JS line hiding this error message directly after loading/DOM creation)

Or we could adjust the usual "No JS" error message to cover these aspects...

### PR DESCRIPTION
**Pull request by rugk**
- [x] I agree to release the changes in this PR under the Zlib/libpng license as shown in the  [LICENSE file](https://github.com/PrivateBin/PrivateBin/blob/master/LICENSE.md#zliblibpng-license-for-privatebin).

This PR fixes #103
## Changes

- added a JS error message, which only is shown when JavaScript is just no loaded, but supported/activated by/in the browser 

It is:
- hidden by JS code executed as early as possible
- not hidden by noscript tags, so that it is _not_ shown when JS is just disabled

I tested it with Chromium's throttling and I did not see the error message as a false-positive:
thottelingprove
## ToDo

- [x] Add code to all templates
- [x] Create & link FAQ

@elrido Please test it and look over it. If everything is all right, I'll finish the TODOs.

### CODE REVIEW

**Comment by rugk** [comment]
If the message is still "too much", we could also change it to a "loading" message - which would not even have to be hidden so fast, and add a note at the bottom stating "If this message does not go away, probably the JavaScript files could not be executed.".

**Comment by elrido** [comment]
I would not readd a message that gets removed by JS at the top. The reason we switched back to the noscript-tag one was that users complained about seeing an error while the site loads on slower servers/connections.

I do like your idea of instead showing a "loading ... if this does not go away, check our FAQ" message and at the bottom (below textarea, but above footer). This would also cover the request for a loading status message while decrypting large pastes etc.

**Comment by rugk** [comment]
> about seeing an error while the site loads on slower servers/connections.

As said I've tested it with thronging and I did not saw it - as I used a document.ready.

So I've now changed it to a loading message.

**Comment by elrido** [comment]
I reviewed it and it looks good.

Have added the missing/updated message IDs to the translation files, did some tweaking of the CSS and also merged it with the master to get rid of the styleCI warnings and simplify the merge back.

When all templates are updated and we have a link for the FAQs (which also needs to be added to all translation files, so translators know it needs translation) we can merge it.

**Comment by rugk** [comment]
So I've did everything except adding the string to the translation files as the `"` of the HTML code causes some inconveniences with the JSON format.
So when you add them, we can merge this.

**Comment by elrido** [comment]
You can [escape the quotes with a backslash](https://github.com/PrivateBin/PrivateBin/blob/master/i18n/de.json#L31) in the translation files.

**Pull request merged**
