### PR TITLE
Update the history when a paste is created

### PR DESCRIPTION
**Pull request by rugk**
Fixes https://github.com/PrivateBin/PrivateBin/issues/167

* [x] I agree to release the changes in this PR under the Zlib/libpng license as shown in the  [LICENSE file](https://github.com/PrivateBin/PrivateBin/blob/master/LICENSE.md#zliblibpng-license-for-privatebin).

This PR fixes 

## Changes

* Added history.pushChanges after paste creation -> updates URL as suggested
* I also needed to add an a history handler, which manually redirects back to the home page when the user clicks on the back button as otherwise just the `?…` URL would vanish without having the user on the "home page" again.
* Also some data about the saved state is added. Maybe we can use this later. 😄

### CODE REVIEW

**Comment by rugk** [comment]
@elrido Do you really need to do all your cleanup/refactoring in this branch? The diff is quite crazy now considering that this PR should just add a small "feature".

**Comment by elrido** [comment]
I did do some refactoring by moving some of the functions to more appropriate places. Wrote unit tests for those moved functions, but am unsure if and how I could mock history pushes and pops, as these seem tied to a browser UI.

I did quite some testing of the new function and can confirm that it works.

What was a bit odd (for me), was that clicking the created link did *not* trigger a reload of the page, as Firefox detected that I was already on that page. This is probably the intended behavior. Middle-clicking it did open it in a new tab, as usual.

If the original page already has some URL parameters, then clicking "back" will change the URL, but not refresh the page content (you will still be on the created paste view). Add for example ?pasteid=&test=test to a PB URL, open it and create a new paste. This is probably a corner case we can ignore.

**Comment by rugk** [comment]
> If the original page already has some URL parameters, then clicking "back" will change the URL, but not refresh the page content (you will still be on the created paste view). Add for example ?pasteid=&test=test to a PB URL, open it and create a new paste. This is probably a corner case we can ignore.

Yes, that's why I strictly compare the URL in the "manual reload" workaround (`historyChange`). And yes, it is a corner case. Nobody should have these parameters in the first place when visiting the home page.

For the other issue I've added a manual trigger, which runs a reload when the link is clicked and otherwise browsers would not reload.

**Comment by rugk** [comment]
We also need to consider the expected behaviour of the "RAW text" button? Without this PR it goes back to the main/home page. (need to check with this PR…)

**Comment by rugk** [comment]
Okay, I did not saw `this.reloadPage`. We can of course only use this…

**Comment by elrido** [comment]
merged

**Comment by rugk** [comment]
I "re-merged" this in https://github.com/PrivateBin/PrivateBin/commit/e483d60eed35ce621ea62971442c4461e99dcaa3. It seems you did not merge this at all, so don't know what got messed up…

**Comment by elrido** [comment]
I actually did, but the other mess probably reverted it.

**Pull request closed without merging**
