### PR TITLE
625 bugfixes - excluding attachment preview handling bugfixes

### PR DESCRIPTION
**Pull request by Haocen**
This PR fixes bugfixes section of #625 

## Changes

1.  Add resource: to script-src cspheader to fix pdf display in Firefox
2.  Cannot paste text into password input dialog
3.  Avoid DOMPurify mess with forward slash in expirationDateString
4.  Fix broken Helper.durationToSeconds, as it doesn't handle weeks
5.  Reload page when back button in browser pressed, avoid reading burn after read paste from cache
6.  Fix TopNav.isAttachmentReadonly logic so dropzone won't show when shouldn't
7.  Change order of execution to detect delete token properly
8.  Sanitize output from Helper.urls2links
9.  Avoid recreation of existing pasteurl element when calling URL shortener
10. Open all links in new window

## ToDo

* [ ] 
* [ ] 
* [ ] 

Test deployment:
https://privatebin-testing.herokuapp.com/

### CODE REVIEW

**Comment by Haocen** [comment]
The attachment preview related bugfixes will be grouped with file name/size display to make some changes make more sense in its surrounding context.

**Comment by elrido** [comment]
The travis unit tests are found [here](https://travis-ci.org/github/PrivateBin/PrivateBin/builds/692846275) - it fails in the [urls2links method](https://travis-ci.org/github/PrivateBin/PrivateBin/jobs/692846280#L490) in privatebin.js, the unrecognised, generated URL was "http://f/".

**Comment by Haocen** [comment]
Sure let me fix it.

**Comment by elrido** [comment]
On my [test instance such links are detected and replaced](https://zerobin-test.dssr.ch/?5ce0a62a366f8450#6KYy2QAFJgcrwF5LT5W5Vt4h8n31bAnRK4nFrkizu2Ep) with your changes.

Both of the failing tests validate that created link contains the `rel="nofollow"` attribute, but it is missing - probably DOMpurify strips it.

https://github.com/PrivateBin/PrivateBin/blob/e59ef24d358192cbf5b8f2b5b4daacfeb70d1052/js/test/Helper.js#L128

You may have to configure DOMpurify to allow the `rel` attribute, similar like it was done at:
https://github.com/PrivateBin/PrivateBin/blob/e59ef24d358192cbf5b8f2b5b4daacfeb70d1052/js/privatebin.js#L727-L735

It will be a bit different, since you have to allow any tags and attributes that can occur in the formatted HTML content of plaintext and source code content. I think that might be what the [`ADD_ATTR` option](https://github.com/cure53/DOMPurify/blame/master/README.md#L173-L174) can be used for?

**Comment by Haocen** [comment]
Hi @elrido thank you very much for the insightful and detailed explanation.
Since we're going to add a hook to DOMPurify to make all links open in new window, I just went ahead and included this change in the PR, I assume this change will fix the tests.

Open all links in new window is technically a feature/enhancement but since we're doing it after all so I hope you don't mind me including this sooner.

**Comment by elrido** [comment]
Well, the tests still fail, because they expect a URL with just `rel="nofollow"` and no `target` and `xlink:show` attributes. Could you please update the unit tests to match your new output at the following two spots?
https://github.com/PrivateBin/PrivateBin/blob/e59ef24d358192cbf5b8f2b5b4daacfeb70d1052/js/test/Helper.js#L128
https://github.com/PrivateBin/PrivateBin/blob/e59ef24d358192cbf5b8f2b5b4daacfeb70d1052/js/test/Helper.js#L148

**Comment by Haocen** [comment]
I made some changes but failed to find out a way to run tests locally.
I think I'm missing Python to be able to build one of the dependency, meanwhile mocha seemed to be missing from `package.json`.

**Comment by elrido** [comment]
I added the target links to the tests in 8fcc321eb6a8561b15b, then the [unit tests found that DOMpurify strips line tabulation characters](https://github.com/PrivateBin/PrivateBin/runs/746540585?check_suite_focus=true#step:6:188) and addressed that in cb0faf690c08befab7.

**Comment by Haocen** [comment]
Thank you! I could never figure this out myself...
At the meantime I'm still struggling when trying to run unit tests on my Windows machine, I'll probably make the unit test a docker container if I figure everything out.

**Comment by elrido** [comment]
Sorry, on Windows you won't be able to access the path `/etc/mimetypes`:
https://github.com/PrivateBin/PrivateBin/blob/master/js/common.js#L43

If you do have docker - we do offer a docker container with both mocha and phpunit preinstalled and instructions to use them both or individually against your repository:
https://hub.docker.com/r/privatebin/unit-testing

**Comment by Haocen** [comment]
Fantastic, I'll give it a try.

**Pull request merged**
