### PR TITLE
Use better random number generator

### LINKED ISSUE #29: Improve random number generation
See https://paragonie.com/blog/2015/07/how-safely-generate-random-strings-and-integers-in-php

So I would propose the following order:
* `Sodium::randombytes_uniform()`
* `random_bytes()`
* [`random_compat`](https://github.com/paragonie/random_compat)? (or current `mcrypt_create_iv` implementation?)

Maybe we'll switch the first two - probably depending on which is faster.

### PR DESCRIPTION
**Pull request by rugk**
* [x] I agree to release the changes in this PR under the Zlib/libpng license as shown in the  [LICENSE file](https://github.com/PrivateBin/PrivateBin/blob/master/LICENSE.md#zliblibpng-license-for-privatebin).

This PR fixes #29 

## Changes

* Replace custom implementation with "random_compat"
* Move the static variable of the Salt path into the method (as an attribute) - just some code styling

### CODE REVIEW

**Comment by rugk** [comment]
@elrido I have assigned you now. This means you should review this and merge it if everything is okay.

I hope we just get no merge issues with https://github.com/PrivateBin/PrivateBin/pull/59 when this is merged, but well... this may happen when you do not exclude the `vendor` dir. The composer devs  have their reasons to recommend this.

**Comment by elrido** [comment]
Could you please resolve the conflict? You need to do a merge against the master branch, resolve the conflicts and then rerun composer (`composer install --no-dev --optimize-autoloader`). Finally push it again, thanks.

And no, that it is not a problem due to the vendor inclusion, this is just what happens if branches diverge and is a regular occurrence in git. We call it merging. :wink:

**Comment by elrido** [comment]
The files in vendor/paragonie/random_compat/lib are missing, so the master will be broken again. I'll merge and add them myself. :disappointed:

**Comment by rugk** [comment]
In my test installation they were there. Maybe a wrong gitignore or some other strange thing.
But well... these are the results of not using Composer the way it is intended to do. It is really bad for developing PrivateBin.

And BTW: The tests passed, so I don't know how files could be missing there.

**Comment by elrido** [comment]
Sorry Dude, please learn to use git. You have the files in your repo, but they were not checked in. Hence I asked to use git add **-f**. Again, this is not bad development, this is just you not understanding git and how to deliver a product.

You saw the ticket by the admin that checked out the project and had issues. If we provide no vendor folder, how many such tickets do you think we would get? Do you honestly think we can expect every user of this project to read a long winded installation procedure. They try it, but from most cases where it fails we never even hear from.

PrivateBin should just be about copying a few files on the server, not about having to then install non-packaged thirdparty tools (composer is neither in Debians nor Ubuntus default package sources) to then run commands on the commandline (how should those with some FTP-account on a cheap sharehoster do that) to complete the installation. Composer is cool for devs, but we can't expect its use (and availability) from every kid that just wants to run the project on its FTP, raspberry pi or whatnot (yes, I am aware that composer runs on ARM, but that's not the point).

**Comment by rugk** [comment]
You may notice that there are many, many contributors not knowing git - or the specific feature of git you suggest.

Additionally I should not *have to* use `git -f`. When I have to use this, this indicates that the `gitignore` excludes the parts I wanted to add and if you say the vendor dir should be submitted you have to *include* it.
So there is this simple rule: If you want contributors to include files, do not exclude them!

So as I really don't like nagging around, here is a PR to fix this: https://github.com/PrivateBin/PrivateBin/pull/83

I'll create a new issue for the general composer discussion. We need to discuss this in one issue and not across multiple issues/PRs as we do currently.

**Pull request merged**
