### PR TITLE
Serverside yourls

### PR DESCRIPTION
**Pull request by jmozd**
This PR adds the server-side YOURLS shortener suggested in https://github.com/PrivateBin/PrivateBin/issues/725#issuecomment-808764580 

## Changes

* added a new PHP page "/shortenviayourls.php", as suggested by Mounir Idrassi
* updated the code to work with PHP8 (as it is used within the current PrivateBin container)
* modified the code to use configuration parameters instead of "change here" elements
* added configuration parameter section "yourls" with parameters "signature" and "apiurl"

## ToDo

* [ ] need php8-curl added to the container image for this to work, see https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/114
* [ ] need Dockerfile to update "PATH" not only on index.php, but shortenviayourls.php as well, see https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/115

### CODE REVIEW

**Comment by elrido** [comment]
Thank you for your initiative! I'm fine with adding this functionality, but would prefer if that new URL endpoint got hooked into the main Controller, similar to the way we display the [JSON-LD](http://json-ld.org/) schemas.

May I collaborate with you on this? I'd provide a branch with my suggested changes and you can merge the parts you like into your branch and adjust/fix what is needed.

**Comment by jmozd** [comment]
> Thank you for your initiative! I'm fine with adding this functionality, but would prefer if that new URL endpoint got hooked into the main Controller, similar to the way we display the [JSON-LD](http://json-ld.org/) schemas.

This definitely is the better approach, from an architectural point of view. Mostly, figuring out the details was above my time budget for this change.

> May I collaborate with you on this? I'd provide a branch with my suggested changes and you can merge the parts you like into your branch and adjust/fix what is needed.

Sounds like an optimum approach - with you providing the framework details, I should be able to update the PR to provide solution integrating with the other parts correctly.

I'll also take that as a starting point to check if I can implement https://github.com/PrivateBin/PrivateBin/issues/833, in a separate PR - I expect to need to better understand the controller setup, your work will help me with that. 

> Edit: I've started that collaborative branch in [master...serverside_yourls]

I'm already going through the changes and yes, of course I'm fine with that :)

**Comment by jmozd** [comment]
@elrido Is there anything I can/should do? Looks like you already did all the work of integrating this into your MVC structure :thumbsup:

**Review by elrido — APPROVED** [review]
Thanks for merging these into your branch.

**Comment by jmozd** [comment]
@elrido It seems that your change to route the yourls request via the MVC framework (instead of using a separate PHP entry point) might have created a need for a different browser-side implementation, too... currently, it's a simple GET request to the URL defined in the config.

**Comment by jmozd** [comment]
@BlackWolfWoof pointed out that setting the baseurl in the way I did caused wrong URLs to be constructed. It needs to end with a "/", instead. Changing that will break the "is this our URL" detection in lib/YourlsProxy.php#L51 - the suffix added there ("/?") for comparison would need to be just the question mark.
But first we need to fix handing in the shortening request at all. @elrido , can you point me in the right direction please, as the MVC implementation had been added by you?

**Review by rugk — COMMENTED** [review]
LGTM codewise, thpough practial testing seem to have shown some issues, so @elrido could you have a look please?

**Pull request merged**
