### PR TITLE
Preview encoding fix

### LINKED ISSUE #588: Preview sourcecode in 1.3.3 is broken
After the update to 1.3.3 it seems that the source code preview is broken. 

## Steps to reproduce
1. Add some example PHP code 
2. Change format to Source code
3. Press preview

### What happens
It's not correct. A lot of strings are removed/stripped. 

### What should happen
Same behaviorus as in 1.3.2. Properly formatted code.

## Additional information
After the downgrade (1.3.2) everything works again. 

## Basic information
**Server OS:**
Linux

**Webserver:**
NGINX

**Browser:** 
Firefox / Chromium

**PrivateBin version:**
1.3.3

I can reproduce this issue on <https://privatebin.net>: Yes

### PR DESCRIPTION
**Pull request by elrido**
This PR fixes #588 - source code / plain text broken when containing HTML tags.

## Changes
* refactor switch into nested if/else, to improve readability - no functional change, but helped me understand the intent of the logic
* revert Helper.urls2links() to be applied on top of HTML elements
* this allows the insertion of strings via text nodes, which makes the browser handle the HTML entity encoding for us

Plain text and source code now render correctly.

Markdown remains unchanged and unknown and risky HTML tags will still get stripped from it - this is intended, as far as I know. In [my tests](https://snip.dssr.ch/?8560054f84df4d13#26GKC5tiNspz58dzWCh1ev7AJEDLXhpKuzorLvAcQqep) I could still insert some HTML code inside of markdown-code blocks (3 backticks) and get a seemingly correct display. Adding the same code without a code block in markdown it got stripped entirely (in the above example link, click "clone", then remove the 3 backticks and switch the "Preview" to see the effect).

### CODE REVIEW

**Comment by rugk** [comment]
Sorry, but I don't get what you actually want to fix here. #588 is about the plaintext view and you describe tests of the Markdown view. You also change the code pretty heavily for all cases there, which makes it pretty hard to review.

Did you actually [read my comment](https://github.com/PrivateBin/PrivateBin/issues/588#issuecomment-591450027)?
You did not take any of that into account in your change.

I guess this can be solved easier and safer than by somehow working around yet another escaping thing and (re)encode, decode etc.

**Comment by elrido** [comment]
I did read your comment and thought you had realized, that pre-tags don't protect against XSS at all, so you still need to do something like DOMpurify to protect against it.

What this change does, like described, is that it prevents DOMpurify from stripping anything resembling tags that it doesn't have whitelisted, by properly encoding all entities, so that they don't pose any risks and any content is displayed as intended.

For context - here is simplified, what the logic below does to the paste, whenever a preview or paste view occurs:
1. When markdown - convert paste to markdown HTML, DOMpurify and display it
2. Otherwise, convert URLs in paste to links, then...
    1. when source code, prettify the paste into HTML
    2. when plain text, only allow a-tags in DOMpurify
3. DOMpurify and display it

https://github.com/PrivateBin/PrivateBin/blob/5340f417e07fdfdab2f91f5171f4f992bc763a73/js/privatebin.js#L2440-L2488

I realized walking through the above logic, that it wasn't the problem, just the urls2links function needed to be extended to properly escape the risky characters.

This change fixes the issue for all formatters and also in the comments (which we hadn't noticed yet). Should I provide you a demo instance so you can test it for yourself?

**Comment by elrido** [comment]
Another attempt to explain this better, since I obviously failed to make myself understood :-(

> Sorry, but I don't get what you actually changed here.

I encode all of the HTML entities for plain text, source code and comments. I do this in the urls2links method, because it is used in all three cases.

If you don't like the logic refactoring, I can remove that commit from the PR, it is non-essential to the fix.

**Comment by elrido** [comment]
Another attempt: As we discovered in [#588](https://github.com/PrivateBin/PrivateBin/issues/588#issuecomment-595399629), back in the old days we had avoided the mess by applying urls2links to an HTML element instead of a string. I reverted my former attempt to fixing urls2links, reverted the urls2links method to the old precedure, merged master to fix StyleCI and applied the regex fix from #591. I kept the refactoring from switch to if statements for clarity.

It works, except for the regex still not capturing the case described, but [only in the source code view](https://zerobin-test.dssr.ch/?4d1b3ab2917b658c#2x4kriiTr3nwGY3HxAtvajS8N6hvj96yGiCGr33VoGKK).
As far as I can tell that is because in that view the URL is split into three different spans, so the regex can't detect it.

Would this PR be acceptable in this state or is it still going the wrong direction?

**Pull request merged**
